### ISSUE TITLE
Add exclude and include options for the OAI config file

### ISSUE THREAD

**Issue by timgloege** [collectiveaccess/providence#1042]
Hi,

It would be really helpful to add “restrictToTypes” and “excludeTypes” options to the OAI config file (oai_provider.conf). It would keep the query string shorter and less complex. DPLA does not accept newspapers, for example, requiring a long string of "OR" clauses in the query to exclude that material from being harvested. Any additional restrictions we might want would need to be added on top of that.

Thanks!

**Comment by collectiveaccess** [comment]
We will add this for you in the next week.

**Comment by collectiveaccess** [comment]
Added feature.

**Comment by timgloege** [comment]
Perfect, thank you!
