### ISSUE TITLE
during providence 1.7.12 install: Can't create table `providence`.`ca_editor_ui_labels` (errno: 150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by 0nobody0** [collectiveaccess/providence#1048]
hello,

trying a fresh install on a test server with:
-  providence 1.7.12
- mariadb 10.5.11
- php 7.4.21
- redis 5.0.3
- nginx 1.14.1

regardless of the profile installation fails with:

`Fatal error: Uncaught DatabaseException: Can't create table `providence`.`ca_editor_ui_labels` (errno: 150 "Foreign key constraint is incorrectly formed") in /usr/share/nginx/html/providence/app/lib/Db/mysqli.php:316 Stack trace: #0 /usr/share/nginx/html/providence/app/lib/Db/DbStatement.php(151): Db_mysqli->execute() #1 /usr/share/nginx/html/providence/app/lib/Db.php(261): DbStatement->executeWithParamsAsArray() #2 /usr/share/nginx/html/providence/install/inc/Installer.php(479): Db->query() #3 /usr/share/nginx/html/providence/install/inc/page2.php(69): Installer->loadSchema() #4 /usr/share/nginx/html/providence/install/index.php(151): require_once('/usr/share/ngin...') #5 {main} thrown in /usr/share/nginx/html/providence/app/lib/Db/mysqli.php on line 316
`

looking at the database the previous tables appear to have been created correctly.

**Comment by collectiveaccess** [comment]
I just pushed a change to the schema to (hopefully) resolve this. Can you pull on the master branch and try installing again?

Thank you.

**Comment by 0nobody0** [comment]
looks like that fixed it, thanks very much
