### ISSUE TITLE
1.7.12 cautils import marks final representation as primary

### ISSUE THREAD

**Issue by 0nobody0** [collectiveaccess/providence#1069]
not sure if this is technically a bug or an intentional change in behavior.

when using cautils to import representations for existing objects: under providence 1.7.8 the first representation imported for an object would be assigned as the primary representation. on 1.7.12 the last representation imported for an object is being assigned as the primary representation.

is there a way to instruct 1.7.12 cautils to label the first representation imported primary rather than the last? or is now something that needs to be specified in the imported data set?

**Comment by collectiveaccess** [comment]
It's basically "undefined" behavior, an artifact of the underlying libraries being used. We can add an option to control for this, but it would be in 1.8. We're not adding new features to 1.7.x at this point.

**Comment by 0nobody0** [comment]
gottit, thanks again

**Comment by collectiveaccess** [comment]
Would an addition to 1.8 work for you? Or do you absolutely need this in 1.7.x?

**Comment by 0nobody0** [comment]
need is a strong word but it would be ideal to have a fix as soon as possible.

currently trying to upgrade from 1.7.8 to 1.7.12 and this is the last issue to work out on the test server. i will try to think of a hack but i am woefully undereducated on sql queries etc. if it came to that. if there is some sort of workaround that you can recommend until 1.8 that would work.

to clarify the context there are 3,000+ objects with 24,000+ representations and the primary image/image order is important for the pawtucket2 instance as well. if it helps all image filenames include a numeric prefix (per object) specifying the order they go in, like in the example at https://collectiveaccess.org/support/index.php?p=/discussion/comment/324013/#Comment_324013.

**Comment by collectiveaccess** [comment]
So this is an existing system? But without these 24,000 images imported yet?

**Comment by 0nobody0** [comment]
there's an existing production server running 1.7.8 with all images imported (the 1.7.8 instance mentioned above where the first image imported was labeled primary). now working on a second test server with updated OS, dependencies etc. and ca 1.7.12. all objects are imported but ran into this problem doing a test import of 10 images for 2 objects before trying all 24,000+.

**Comment by collectiveaccess** [comment]
Got it. And the problem was the primary flag? Anything else going wrong?

**Comment by 0nobody0** [comment]
everything with providence seems to be going great (haven't set up pawtucket yet).

**Comment by collectiveaccess** [comment]
I finally got around to testing this and can't see a problem. The first file encountered is set as primary, others as non-primary, both in 1.7.12 and 1.8.

**Comment by collectiveaccess** [comment]
It's possible the issue is the order in which the files are being read off of the disk, as we're just taking what we get from scandir() and importing them one-by-one. I'm going to add sorting to the filename read, so at least it's predictable. This'll be in 1.8 and GitHub master (current 1.7.12). Try pulling it and seeing if it makes a difference.

**Comment by 0nobody0** [comment]
thanks very much - unfortunately the same issue seems to be happening on a clean install with the new commits - maybe a wacky importer setup on my end? apologies for the inconvenience.

the log seems to indicate the files importing in the correct order but '02 Test Image 2.jpg' is still automatically set as primary:

```
2021-09-15 23:28:45 - INFO --> Started import of /usr/share/nginx/html/providence/import/test.xlsx using mapping photo
2021-09-15 23:28:45 - INFO --> [ITEM000008] Merged with existing record matched on identifer by policy merge_on_idno
2021-09-15 23:28:50 - INFO --> Created new object representation 01 Test Image 1
2021-09-15 23:28:50 - INFO --> [ITEM000008] Imported  as ca_objects
2021-09-15 23:28:50 - INFO --> [ITEM000008] Merged with existing record matched on identifer by policy merge_on_idno
2021-09-15 23:28:55 - INFO --> Created new object representation 02 Test Image 2
2021-09-15 23:28:55 - INFO --> [ITEM000008] Imported  as ca_objects
2021-09-15 23:28:55 - INFO --> Import of /usr/share/nginx/html/providence/import/test.xlsx completed using mapping photo: 2 imported/0 skipped/0 errors
```

for this test there is only the one object in the system. here is the imported data:
![testdata](https://user-images.githubusercontent.com/7801211/133562531-afc9ef55-6157-45a2-b153-5e1ed3625da7.jpg)

and the importer settings:
![importer](https://user-images.githubusercontent.com/7801211/133562540-9a2c9b0c-3667-4a1b-873c-cb2e94727994.jpg)
![importer2](https://user-images.githubusercontent.com/7801211/133562548-d24331f3-7f6a-4aa0-88da-ae0617e1cc59.jpg)

**Comment by collectiveaccess** [comment]
I just pushed another change to 1.7.12 (master). Can you do a pull and try again?

**Comment by 0nobody0** [comment]
just pulled the change and unfortunately no difference from the previous log/behavior

in case it's relevant here are the versions running on the server:
- nginx 1.14.1-9
- mariadb 10.5.12-1
- php 7.4.23-1
- redis 5.0.3-2

**Comment by collectiveaccess** [comment]
Can you send me your mapping?

**Comment by 0nobody0** [comment]
sure - just emailed

**Comment by collectiveaccess** [comment]
Just pushed a new change to resolve this.

**Comment by collectiveaccess** [comment]
In both 1.7.12 (master) and develop

**Comment by 0nobody0** [comment]
that did the trick - many many many thanks
