### ISSUE TITLE
For search endpoint, add the ability to create record if record is not found

### ISSUE THREAD

**Issue by wykhuh** [collectiveaccess/providence#1095]
When creating relationships, we have to  make one API call to search for the record.  If the record doesn't exist,  we have to make another API call to create the record. Then we make another API call to create the relationship.    Can we simplify the process to reduce the number of API calls?

Possible options
- pass in an option so the search endpoint will create the record if record is not found; return the id/idno of the new record

**Comment by collectiveaccess** [comment]
Added new "match" and "matchOn" options to add mutation. See https://github.com/collectiveaccess/providence/commit/6a2cf80b866c3a971b087c3b53e1459b6cf73445.

Docs are updated to reflect new options:
