### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by zidingz** [collectiveaccess/providence#1143]
Hey there!

I belong to an open source security research community, and a member (@noobpk) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by collectiveaccess** [comment]
We've just added a SECURITY.md file. Thanks for the suggestion – always a good idea to have one. You can contact us at support@collectiveaccess.org.

**Comment by collectiveaccess** [comment]
PS. I see the reports on huntr.dev. Thanks for doing this work. It's extremely helpful.
