### ISSUE TITLE
loading providence/install on develop branch results in Fatal error: Uncaught Error: Call to undefined function caGetLoginLogo()

### ISSUE THREAD

**Issue by 0nobody0** [collectiveaccess/providence#1176]
loading http://localhost/providence/install in a browser on a fresh git clone of the develop branch returns the following:

`Fatal error: Uncaught Error: Call to undefined function caGetLoginLogo() in /usr/share/nginx/html/providence/themes/default/views/system/configuration_error_html.php:47 Stack trace: #0 /usr/share/nginx/html/providence/app/helpers/requestHelpers.php(147): require_once() #1 /usr/share/nginx/html/providence/app/helpers/post-setup.php(319): caCheckVendorLibraries() #2 /usr/share/nginx/html/providence/setup.php(221): require('/usr/share/ngin...') #3 /usr/share/nginx/html/providence/install/index.php(45): require_once('/usr/share/ngin...') #4 {main} thrown in /usr/share/nginx/html/providence/themes/default/views/system/configuration_error_html.php on line 47`

temporarily resolved by removing line 47 from providence/themes/default/views/system/configuration_error_html.php - not urgent at all but just got reminded of this when it was replicated on a second test server using

- nginx 1.14.1-9
- mariadb 10.5.12-1
- php 7.4.24-1

one strange thing is after this caGetLoginLogo() seems to work fine on the other pages it is used - login pages etc.

originally mentioned in issue [#1134](https://github.com/collectiveaccess/providence/issues/1134#issuecomment-924153080)

**Comment by 0nobody0** [comment]
this also showed up while doing testing on a server with

- MySQL 5.7.30-1
- php 7.2.11-2

**Comment by collectiveaccess** [comment]
Fixed the logo display error. I'm not sure about the composer error – composer does fail sometimes and there's not much we can do about it.

**Comment by 0nobody0** [comment]
testing a fresh develop clone - http://localhost/providence/install/ returns

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>CollectiveAccess configuration error display</title>
	<link href="<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function caGetThemeUrlPath() in /usr/share/nginx/html/providence/themes/default/views/system/configuration_error_html.php:41
Stack trace:
#0 /usr/share/nginx/html/providence/app/helpers/requestHelpers.php(147): require_once()
#1 /usr/share/nginx/html/providence/app/helpers/post-setup.php(319): caCheckVendorLibraries()
#2 /usr/share/nginx/html/providence/setup.php(221): require('/usr/share/ngin...')
#3 /usr/share/nginx/html/providence/install/index.php(45): require_once('/usr/share/ngin...')
#4 {main}
  thrown in <b>/usr/share/nginx/html/providence/themes/default/views/system/configuration_error_html.php</b> on line <b>41</b><br />
```

http://localhost/providence displays the full configuration error page correctly:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>CollectiveAccess configuration error display</title>
	<link href="/providence/themes/default/css/error.css" rel="stylesheet" type="text/css" media='all'/>
	<link href='../assets/fontawesome/css/all.min.css' rel='stylesheet' type='text/css' media='all'/>
	<link href='../assets/fontawesome/css/v4-shims.min.css' rel='stylesheet' type='text/css' media='all'/>
</head>
<body>
	<div id='box'>
		<div id="logo"><img src=/providence/themes/default/graphics/logos/logo.svg alt='CollectiveAccess logo' width='327' height='45'/></div><!-- end logo -->
		<div id="content">
			<div class='error'>There are issues with your configuration</div>
				<div class='errorDescription'>General installation instructions can be found
				<a href='https://manual.collectiveaccess.org/setup/Installation.html' target='_blank'>here</a>.
				or more specific information on detected issues review the messages below:</div>			<div class="permissionError">
								Your installation is missing required vendor libraries. This is normal if you have just installed from a Git branch. <a href='index.php?updateVendor=1'><strong>Click here</strong></a> to automatically load the required libraries, or see the <a href="http://docs.collectiveaccess.org/wiki/Installing_Vendor_Libraries">wiki</a> for instructions on installing the required libraries manually. <strong>NOTE: Installation may take some time.</strong>				<div style='clear:both; height:1px;'><!-- empty --></div>
			</div>
			<br/>
		</div><!-- end content -->
	</div><!-- end box -->
</body>
</html>
```

**Comment by collectiveaccess** [comment]
None of these line numbers match anything I have. And it makes no send that line 54 of errorHelpers.php would require itself. (I can't find that code either). The only place "require("./app/helpers/errorHelpers.php");" appears is in the main index.php entry point, right at the top. So either this some odd nginx-specific thing, or something in your report is scrambled.

**Comment by 0nobody0** [comment]
just edited the comment above to remove the require issue - had been messing with install/index.php to investigate the Uncaught Error: Call to undefined function caGetThemeUrlPath() and forgot to revert it.
