### ISSUE TITLE
Increase the usage of expressions with combined operators

### ISSUE THREAD

**Issue by elfring** [collectiveaccess/providence#1225]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#(?<target>\$\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+/%^.]|-(?!>)|&(?!&)|\|(?!\|)|\*\*?|<<|>>|\?\?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/Providence/lokal -name '*.php')
```

**Comment by elfring** [comment]
I would appreciate another bit of constructive feedback. :thinking:

**Comment by elfring** [comment]
I propose to adjust a few implementation details in some source files.
🔮 Will the support grow also for [the application of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") according to the programming language „PHP“?

**Comment by collectiveaccess** [comment]
Which files?

**Comment by elfring** [comment]
* :thought_balloon: Would you dare to try the shown Perl command example out on another development repository?
* How much do you understand from the proposed source code transformation approach so far? :thinking:

**Comment by elfring** [comment]
Software run time characteristics can be influenced in desirable directions if each parameter will be evaluated only once by combined operators, can't they? :thinking:

**Comment by elfring** [comment]
Not yet. ‒  💭 I became curious if you would like to take another look at change possibilities.
