### ISSUE TITLE
No local dateformat in timeline function

### ISSUE THREAD

**Issue by martin1huber** [collectiveaccess/providence#1322]
The date in the first line(screenshot) is displayed as US format, it needs to be in local format(DE,German).
The default locale in setup.php is set to de_DE. I also attached my visualization.conf file.
![grafik](https://user-images.githubusercontent.com/100099209/154868159-bb2d3368-148e-4d8d-b309-709fb7ef2487.png)
[visualization.odt](https://github.com/collectiveaccess/providence/files/8105123/visualization.odt)

**Comment by collectiveaccess** [comment]
Resolved by e60d40c5d4e11ae1baecf1c4a5ad56934cd40f7c
