### ISSUE TITLE
Thumbnail generator

### ISSUE THREAD

**Issue by vatoz** [collectiveaccess/providence#1324]
Since  commit  f1934194ed35fc99dd132b1ef649789c7beddb76   (in master) generate thumbnails ceased to work.

I have tracked two different errors.
First one is this - it was calling GD function on machine with GD disabled.
I dont have a fix for it.

`[01-Mar-2022 15:51:03 Europe/Prague] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefromjpeg() in /var/www/providence/app/lib/Parsers/TilepicParser.php:1575
Stack trace:
#0 /var/www/providence/app/lib/Parsers/TilepicParser.php(326): TilepicParser->encode_gd()
#1 /var/www/providence/app/lib/Plugins/Media/ImageMagick.php(834): TilepicParser->encode()
#2 /var/www/providence/app/lib/Media.php(284): WLPlugMediaImageMagick->write()
#3 /var/www/providence/app/lib/Plugins/TaskQueueHandlers/mediaproc.php(360): Media->write()
#4 /var/www/providence/app/lib/TaskQueue.php(328): WLPlugTaskQueueHandlermediaproc->process()
#5 /var/www/providence/app/lib/Utils/CLIUtils.php(738): TaskQueue->processQueue()
#6 /var/www/providence/support/bin/caUtils(167): CLIUtils::process_task_queue()
#7 {main}
  thrown in /var/www/providence/app/lib/Parsers/TilepicParser.php on line 1575
`

Second  and third error (found after changing installed packages on debug server)  -  Instead  of exec, new code uitilizes new systemHelper, which was not included in your commit.

`[02-Mar-2022 15:10:03 Europe/Prague] PHP Fatal error:  Uncaught Error: Call to undefined function caExec() in /var/www/providence/app/lib/Parsers/TilepicParser.php:366
Stack trace:
#0 /var/www/providence/app/lib/Parsers/TilepicParser.php(801): TilepicParser->_graphicsMagickRead()
#1 /var/www/providence/app/lib/Parsers/TilepicParser.php(332): TilepicParser->encode_graphicsmagick()
#2 /var/www/providence/app/lib/Plugins/Media/GraphicsMagick.php(830): TilepicParser->encode()
#3 /var/www/providence/app/lib/Media.php(284): WLPlugMediaGraphicsMagick->write()
#4 /var/www/providence/app/lib/Plugins/TaskQueueHandlers/mediaproc.php(360): Media->write()
#5 /var/www/providence/app/lib/TaskQueue.php(328): WLPlugTaskQueueHandlermediaproc->process()
#6 /var/www/providence/app/lib/Utils/CLIUtils.php(738): TaskQueue->processQueue()
#7 /var/www/providence/support/bin/caUtils(167): CLIUtils::process_task_queue()
#8 {main}
  thrown in /var/www/providence/app/lib/Parsers/TilepicParser.php on line 366
`

New code also relies on fact that function caMediaPluginImageMagickInstalled  also return  full path.
I have prepared very dumb quick fix  (see my newest PR) by copying  files from devel branch to master. 
It could broke some other functions.

**Comment by collectiveaccess** [comment]
Do you have ImageMagick or GraphicsMagick installed?

**Comment by vatoz** [comment]
I have both.

**Comment by collectiveaccess** [comment]
Thanks for this. I've just pushed a fix.
