### ISSUE TITLE
Underscores removed from path when looking for tmp/

### ISSUE THREAD

**Issue by I-is-as-I-does** [collectiveaccess/providence#1329]
When looking for the tmp/ folder, underscores seem to be removed from path.
So, path is broken and installation can't succeed.

Example
Actual path to tmp/: C:/_xampp/tmp
Providence looking for it at C:/xampp/tmp
Creating C:/xampp/tmp "fix" the issue.

**Comment by collectiveaccess** [comment]
I have tested both the 1.7.13 release and develop on Mac OS and Linux, and there is no problem. Perhaps it's an issue with XAMPP or our code on Windows – we don't generally test with Windows. I'll try to set up a XAMPP environment in the next few days to track down the issue, if there is one.
