### ISSUE TITLE
Entity Lookup Seems to Not Work

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1342]
I just setup Providence v1.7.14 for the first time.

When I created the first Collection, I added a Corporate body with Surname/organization and the Display name both set to "Bureau of the Census".  When I created the second Collection as a child to the first, I could not find any way to input the same entity again as a Creator.  It always says "Bureau of the Census does not exist. Create?"  And if I click on that, it just creates a duplicate with the same name.

I might be missing some obvious purpose here, but it's not making much sense as a new admin user.

**Comment by collectiveaccess** [comment]
After it's created the first time subsequent lookups should find the name. If it's not finding it, it's possible the indexing is not being triggered. Than can happen on some server setups, although it's not typical. Try setting `disable_out_of_process_search_indexing = 1 i`n your app.conf config file. That'll force indexing to take place in the same process as the request. It can make saving records a bit slower, but guarantees indexing will be done no matter what.

**Comment by miqrogroove** [comment]
I see that file mentions host name resolution.  My server goes by several names.  I don't see any mention of host name on the Configuration Check screen.  Should I hard code it in the app/helpers/post-setup.php file?

**Comment by collectiveaccess** [comment]
You can override any of the constants set in post-setup.php in setup.php, if you wish. Rather than mucking with that at this point, I'd set the indexing setting in app.conf and see if that resolves the issue. Then at least you can be sure of the problem you're dealing with.

**Comment by miqrogroove** [comment]
Actually, I do see the correct value in HTTP_HOST, so I will try the indexing setting.

**Comment by miqrogroove** [comment]
Yep, that fixed it.  The only other thing I can think is that I'm using the recommended SSLStrictSNIVHostCheck on setting.  If the out of process request is non-SNI it will be totally ignored.

**Comment by miqrogroove** [comment]
It just occurred to me while troubleshooting the PDF renderer that I have HTTP Auth enabled and probably need some kind of exception for these internal requests to work on Collective Access.
