### ISSUE TITLE
Extent Element Conflict in dacs_heritage

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1344]
It appears to be impossible to template the data referenced by this metadata element:

https://github.com/collectiveaccess/providence/blob/9949a4a0c51434cfb99d324a4c02789c02a0f528/install/profiles/xml/dacs_heritage.xml#L1178

This conflicts with the intrinsic field `ca_objects.extent` et al.

In the UI editor, it also looks like there are 3 different Extent bundles.

I was able to work around this by creating a new element with a unique name and swap it out in the UI editor.

**Comment by collectiveaccess** [comment]
The name should be changed
