### ISSUE TITLE
Non location History tracking policies

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1345]
Somewhere between 1.8RC5 and the current develop branch the History Tracking has stopped working for non storage locations. In my case for occurrences.  The 'Add Occurrences' link is there, but when you click it, it does nothing.  If I check out 1.8RC5 branch, then it works again.

**Comment by collectiveaccess** [comment]
Is there anything in the browser console? Sounds like it could be a javascript error.

**Comment by collectiveaccess** [comment]
Thanks for catching this. There was some reorganization and those buttons were broken in the process. I just pushed changes to resolve this.

**Comment by Monica-Wood** [comment]
Can confirm it's working as expected now.
