### ISSUE TITLE
Bug/path mistake identified on BrowseListItems (rc5 and reproduced on demo server)

### ISSUE THREAD

**Issue by ra-lb** [collectiveaccess/providence#1346]
To reproduce: 
On the Manage menu, click on List & Vocabularies, then browse. 
Find a filter that will give you a list larger than the list limit (new will do it for me, and one can also lower the limit).

Navigating with the top Next and Previous will work but the bottom one will give out an error: ApplicationException: Invalid controller path

They both look to send you to the same path but inspecting the underlying code gives you two different snippets.

```
<a href="#" onclick="jQuery(&quot;#resultBox&quot;).load(&quot;/ca/index.php/administrate/setup/BrowseListItems/Index/page/4&quot;); return false;" class="button">‹ Previous</a>

<a href="#" onclick="jQuery(&quot;#resultBox&quot;).load(&quot;/ca/index.php/find/BrowseListItems/Index/page/4&quot;); return false;" class="button">‹ Previous</a>
```

Notice the ../find/ instead of /administrate/setup/ in the bottom one. 

I reckon you will find the responsible file and lines faster than I could, so I'll leave it at that.

**Comment by collectiveaccess** [comment]
Thanks for raising the issue. Fixes are in master and develop.
