### ISSUE TITLE
Image Corruption With Rotated Orientation

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1348]
When uploading image files tagged with a rotated orientation, Providence displays a highly distorted thumbnail, and generates tiles in the wrong order.

This is Providence v1.7.14 with Gmagick

Expected result:
![example](https://user-images.githubusercontent.com/1371835/175327141-145aa484-7b55-4168-84c6-1734f74f4b80.jpg)

Actual thumbnail:
![test-thumb](https://user-images.githubusercontent.com/1371835/175327342-6158ebc1-3ecd-4dc3-811b-9afb424dbf24.jpg)

Actual tile view:
![test-tile](https://user-images.githubusercontent.com/1371835/175327761-0e60d71f-6ee5-460d-b709-b4b2631b70d9.jpg)

Original image:
![test-image](https://user-images.githubusercontent.com/1371835/175327850-aad97c89-7132-4e3b-aa7a-178b807bd5e5.jpg)

**Comment by collectiveaccess** [comment]
This is related to handling of the exif orientation field and is fixed in 1.7.15.

**Comment by miqrogroove** [comment]
Ah I didn't see the new release yet.  I will try that.
