### ISSUE TITLE
dowload list of objects as PDF not displaying images

### ISSUE THREAD

**Issue by atmansviluppo** [collectiveaccess/providence#1365]
I updated my local providence version from 1.7.11 to 1.7.16 and now I am checking if everything is working well (then I will update production). When I download a list of objects as PDF (checklist or thumbnails), all images are displayed with the message "**Image not found or type unkown**" as following:

![Screenshot from 2022-08-31 10-52-07](https://user-images.githubusercontent.com/108877778/187640246-8998d251-ba2f-4683-a2a0-49a89ccaddb0.png)

So I realized that the current providence version uses `getMediaUrl` to get the media path, instead of `getMediaPath` used in 1.7.11 version (commit 2680027ac866e0c5e16afc8b02bc1bee25b7216a):

https://github.com/collectiveaccess/providence/blob/6c99eebd636e771abe7d93937d979cc6a75e7341/app/printTemplates/sets/checklist.php#L79

https://github.com/collectiveaccess/providence/blob/6c99eebd636e771abe7d93937d979cc6a75e7341/app/printTemplates/results/thumbnails.php#L74

When I change the method to `getMediaPath`, all images are diplayed correctly. I don't know if this is a real issue or if the problem could be that I am serving locally using http protocol and a port number or anything else.

Thank you!

**Comment by collectiveaccess** [comment]
This was done to accommodate new security restrictions in domPDF, the library used to generate the PDF output. Can URLs generated to your site be resolved from the server itself? If you try to load a URL for an image held by CollectiveAccess from the server does it load?

**Comment by atmansviluppo** [comment]
You are right! As I am developing using minikube, the providence container can't resolve the minikube ip. And I don't know how to configure it, but I _think_ this will not be a problem in production.
So in this case, is it more secure using the image url's, instead of local path?
Thank you!

**Comment by collectiveaccess** [comment]
DomPDF now "sandboxes" path references, and if you're using symlinks (for instance) the sandboxing can prevent images from loading. Loading by URL avoids the restrictions and is arguably more secure as you're not poking around the file system, but it only works if urls resolve from the server.

**Comment by miqrogroove** [comment]
As mentioned in #1352 this needs to be added to the Configuration Check page.  It would help prevent a lot of headaches.

**Comment by atmansviluppo** [comment]
I will close this issue because I fixed the problem in my development environment and now the providence container can resolve the site URL. I agree with @miqrogroove, it would be nice to have it in the Configuration Check page. Thank you!
