### ISSUE TITLE
Session Always Fails at Midnight

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1371]
Using Providence 1.7.15, I noticed that any time I'm working late, the first request made after midnight always fails and redirects me to the login screen.  I've noticed this several times and just feel like it's unnecessary to have the user session tied to the local calendar date.

**Comment by collectiveaccess** [comment]
It's not. Most likely your cache directory is being emptied at that time.

**Comment by miqrogroove** [comment]
When I installed Providence, I changed the default backend setting as follows in `setup.php`:

```
if (!defined('__CA_CACHE_BACKEND__')) { 
	define('__CA_CACHE_BACKEND__', 'apc');
}
```

Is that relevant?

**Comment by collectiveaccess** [comment]
Yes, APC uses shared memory and the shared memory is being cleared.
