### ISSUE TITLE
Entity Quick Add Doesn't Work on Phone

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1373]
From the Related entities field when creating a new Object, if I tap "does not exist.  Create?" then the Entity quick add dialog goes off the edges of the screen and fails to scroll, making the entire page unusable.

Seen on Chrome for Android.

**Comment by collectiveaccess** [comment]
Will address in a future refactor of the UI.

**Comment by miqrogroove** [comment]
Still having this issue.

The workaround is to leave the object editor, create a new Entity from the main menu, and then return to the object editor to link the new Entity.
