### ISSUE TITLE
Collection Summary Display throwing exception

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1405]
The Collection Summary screen is throwing an exception when the collection has children records.
Works fine with standalone record, or a record at the bottom of the hierarchy. 

Using dev/php8 branch

Stacktrace
```
Invalid numeric operator: is in /var/www/ca/app/lib/BaseModel.php line 12173:
In BaseModel::find() in LabelableBaseModelWithAttributes line 685
At LabelableBaseModelWithAttributes::find() in ca_collections line 543
At ca_collections->hierarchyWithTemplate() in summary_html line 71
At require() in View line 329
At View->_render() in View line 297
At View->render() in ActionController line 162
At ActionController->render() in BaseEditorController line 721
At BaseEditorController->Summary() in RequestDispatcher line 284
At RequestDispatcher->dispatch() in AppController line 114
At AppController->dispatch() in index line 119
```

**Comment by collectiveaccess** [comment]
I'm guessing you don't have `ca_objects_x_collections_hierarchy_relationship_type` set? It needs to be. Of course, we should catch this earlier and provide an error message that points out the actual issue, not a side-effect. I'll fix that.
