### ISSUE TITLE
Relationship types dropdown on related table list bundle

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1406]
I have tested this on both the dev/php8 branch and on the code the demo is running on.

When you limit relationship types to certain record types on the different sides, the related table list bundle doesn't honour this and shows them all.

The normal related table bundle (that shows the bubbles) is working correctly, it's just the related list that isn't.

My steps to reproduce:

1.  Go to entity<->entity relationship types and limit the relationship 'spouse of' and 'child of' to be individual to individual only.
2. Add related entity list in the entity UI.  
3. Go to an Organisation entity record and search for an individual entity in the related entity list bundle.  Select an individual record.  The spouse of, parent of and child of relationships are displayed, when they shouldn't.

**Comment by collectiveaccess** [comment]
Just pushed a fix for this to develop and dev/php8. Please confirm that it works for you when you can.

**Comment by Monica-Wood** [comment]
This has fixed the relationship type list. It's only showing the correct relationship types now.

However I have just noticed that the relationship type being displayed in the related table list bundle is showing the wrong side.
Eg. if you have the child of/parent of relationship type, the related list is showing the wrong side, while the bubble related bundle list shows the correct one. (See screen shot)

<img width="759" alt="Screen Shot 2023-03-19 at 11 08 40 am" src="https://user-images.githubusercontent.com/25235893/226146562-6c7f81a5-5dd1-44be-a82f-3953d439055c.png">

This change didn't introduce this bug, I believe it was already there.

**Comment by collectiveaccess** [comment]
I see. I just pushed another change to resolve this.
