### ISSUE TITLE
global configs not available in local/*.conf files

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1419]
I have found that using global configs like `<ca_base_dir>` are not read correctly when used in config files like `app/conf/local/app.conf`
I discovered this when copying the media uploader settings from app.conf to local/app.conf and I got an error about uploads directory not existing. But when I commented out the line `media_uploader_root_directory = <ca_base_dir>/uploads` everything worked correctly again.

This is on dev/php8, I haven't confirmed it's doing the same thing on other branches yet.

**Comment by kehh** [comment]
Have you tried using the defined PHP constants? See globals.conf for information on how to use those?
something like this:
```
media_uploader_root_directory = __CA_BASE_DIR__/uploads
```

**Comment by kehh** [comment]
I like to use the constants in setup.php because those can then be set by environment variable.

**Comment by Monica-Wood** [comment]
It's not that I really need to set that configuration here and yes, the constants could be used instead for this instant. 
It's more than others will copy the entire app.conf from app/conf/app.conf to app/conf/local/app.conf (as it recommends in the documentation) and then edit what they need, instead of only bring configurations over that they are overriding.  So if these global settings don't work, then they will come across all sorts of issues. And others won't necessarily have the technical knowledge to realise why it's not working.

**Comment by kehh** [comment]
Ah I try to only put overrides in local config files wherever possible. It means default config changes carry through with updates from upstream.

**Comment by kehh** [comment]
Ah I try to only put overrides in local config files wherever possible. It means default config changes carry through with updates from upstream.

**Comment by collectiveaccess** [comment]
I have tested these on both dev/php8 and develop. It all works fine for me. I'd take another look at your local app.conf file. If the issue persists please send me the file to look at.

**Comment by Monica-Wood** [comment]
> I have tested these on both dev/php8 and develop. It all works fine for me. I'd take another look at your local app.conf file. If the issue persists please send me the file to look at.

I have gone and tested this a bit more and it seems to only be doing this on the one install, so I will need to investigate a bit further why it's triggering this... the app.conf in question is a very long and complicated one that I've inherited.  Let's close this and I'll open another one if I ever figure it out and turns out it needs action.

Thanks.
