### ISSUE TITLE
Access field on nonpreferred_labels defaulting to top of list, not default

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1424]
The not accessible option is set as the default everywhere, and this works as expected on the access field for the record, media and preferred_labels, but the access field for the nonpreferred_labels is just showing the value at the top of the list. I have gotten around this by setting the access_statues list to sort by rank, but I did have it sorted by label initially.

Confirmed behaviour on dev/php and develop

**Comment by collectiveaccess** [comment]
Just pushed a fix for this to develop and dev/php8. Please let me know how it works for you.
