### ISSUE TITLE
Sorting options for metadata in Object editor UI

### ISSUE THREAD

**Issue by andrea-favarin** [collectiveaccess/providence#1431]
About sorting the metadata values, now i see the option to choose the metadata to sort by, but in the ui object i don't see the sorted fields.
I also ran the caUtils reload-attribute-sortable-values but I don't see the sorted values. 

![fig1](https://github.com/collectiveaccess/providence/assets/106085642/505a2327-37e3-416b-98eb-473df4367e1f)
![fig21](https://github.com/collectiveaccess/providence/assets/106085642/041522b7-86ef-44f3-9bbc-7ec012ce4321)

**Comment by collectiveaccess** [comment]
Fixed in develop

**Comment by andrea-favarin** [comment]
Many thanks for solving the problem, for my client it was a very important requirement.
Just be careful because on line 832 of the file
app/models/ca_attributes.php there are two commas

**Comment by collectiveaccess** [comment]
Thanks for catching that.
