### ISSUE TITLE
Import bug introduced

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1454]
Wanted to log this somewhere incase it was an obvious fix while I investigate further.

On Develop branch, most recent commit https://github.com/collectiveaccess/providence/commit/5762e821178576d93460dcb5239e38a1bd1a9aa2 

before performing a pull, the most recent commit was around 17 May

Importing records is missing the username/userId and causing timeouts when using the recent changes widget.

Will update if I discover more.

**Comment by collectiveaccess** [comment]
What do you mean by missing username? Are log entries not getting associated user_ids?

**Comment by Monica-Wood** [comment]
Yes the logs, it's just blank where the username is. The Recent Changes shows who made the changes usually and this is also blank and causes the dashboard to either timeout or take a long time to load.   This started happening with imports straight after a pull 2 days ago.

**Comment by Monica-Wood** [comment]
![Screen Shot 2023-06-28 at 13 57 35 pm](https://github.com/collectiveaccess/providence/assets/25235893/2b6b5717-d0dc-4dc8-a9a4-dd195ed08520)

**Comment by Monica-Wood** [comment]
Also on dev/php8 
Narrowed it down to happening somewhere between the 8 June and 26 June

**Comment by collectiveaccess** [comment]
What user did it log when you ran imports before then? Imports on the command line aren't actually associated with a specific user.

**Comment by Monica-Wood** [comment]
These are imports from the UI, not the command line. (Unless running it as a background process would do this).  Before this data, it recorded the user that ran the import.

example log of importing the same way with what I assume is the same mapping the day prior to the update (git pull)
![Screen Shot 2023-06-28 at 14 26 21 pm](https://github.com/collectiveaccess/providence/assets/25235893/b93df312-2fb9-4c33-ac36-9e37b303c6fa)

**Comment by collectiveaccess** [comment]
Running current pull of dev/php8 UI imports do set user in the change log. You're running these in the background?

**Comment by collectiveaccess** [comment]
Please do a pull on develop and/or dev/php8 and try import again. It should associate the user with the log entries now.

**Comment by Monica-Wood** [comment]
I do know the ones dated 28 June were done as background, I can't tell you for sure about the other ones.  So it's very possible that this is only happening to ones processed in background.

I guess the issue isn't just that there is no username attached to the logs, it's that having the recent changes widget on the dashboard is causing 504 timeouts when there is no username.

**Comment by Monica-Wood** [comment]
Hi Seth,  I've confirmed the fix works on php8 branch. Will confirm the develop branch soon hopefully.
