### ISSUE TITLE
Interstitial editor not re-populating the relationship type dropdown in main UI after editing

### ISSUE THREAD

**Issue by kehh** [collectiveaccess/providence#1459]
Code from latest develop and also replicated on demo server:

Steps to replicate this issue:

1. Create an interstitial metadata element (element on a relationship)
2. Create a UI for this relationship if it doesn't exist
3. Create a screen for this UI if it doesn't exist
4. Place new metadata element on new UI
5. Create a relationship between two records of the types represented by the interstitial
6. Save record
7. Open up interstitial modal dialogue (paperclip)
8. Save changes to interstitial
9. Voila contents of relationship are hidden until you reload the screen

[Screencast from 2023-07-03 10-20-22.webm](https://github.com/collectiveaccess/providence/assets/12571/435f1228-def6-4d3b-b3b1-8b195e25595b)

**Comment by collectiveaccess** [comment]
I just pushed a fix for this issue. Please test and let me know if this works for your situation.

**Comment by kehh** [comment]
Yes this works a charm thanks
