### ISSUE TITLE
Warning: Undefined variable on standard editor (php8 branch)

### ISSUE THREAD

**Issue by MRMarchivist** [collectiveaccess/providence#1463]
Upgraded to dev/php8 branch and now receiving warning on the editor page when opening up an item (collections, objects, etc).

**Warnings:
Undefined variable $force_values [/var/www/html/ca/themes/default/views/bundles/ca_storage_locations.php:396]**

Locations are still showing properly. Does not appear on Summary page.

**Comment by collectiveaccess** [comment]
Thanks for pointing this out. It has been fixed in the branch now.
