### ISSUE TITLE
Undefined array key warnings

### ISSUE THREAD

**Issue by MRMarchivist** [collectiveaccess/providence#1465]
dev/php8, upgraded from 1.7.17

After import, objects at the item level display the following warning in editor: 

**Warnings:
Undefined array key "dont_include_subtypes_in_type_restriction" [/var/www/html/ca/themes/default/views/bundles/ca_object_lots.php:85]
Undefined array key "list_format" [/var/www/html/ca/themes/default/views/bundles/ca_object_lots.php:130]
Undefined array key "dont_include_subtypes_in_type_restriction" [/var/www/html/ca/themes/default/views/bundles/ca_collections.php:67]
Undefined array key "list_format" [/var/www/html/ca/themes/default/views/bundles/ca_collections.php:116]**

Editor works fine otherwise and all data present.

**Comment by collectiveaccess** [comment]
These warnings are harmless and a legacy of CA being a pre-PHP 7.0 codebase (some parts of it date to PHP 3 believe it or not). Things that were once common practice in PHP became warnings or even errors in PHP 8. We do appreciate your telling us when you see these as we can then make changes to prevent their triggering in the future. However it may be easier for you to disable on-page display and just log them to a file. You can then work normally and periodically examine the file. Sending us the file once it has a number of messages in it would be helpful as well.

To disable on-screen display set `display_warnings = 0` in `app.conf`. They will still be written to the warning log in `app/log/warning_log.txt`. display_warnings is currently enabled by default to assist us in refining this PHP 8 version. But seeing those warning can be annoying or distracting if you're using this day-to-day.

**Comment by MRMarchivist** [comment]
Thanks for letting me know how to do that! Obviously, if something really weird happens, I'll report issues. I'll turn it off in the meantime.
