### ISSUE TITLE
Media Importer in dev/php8 will only import from (user) folders, not from the (all users) folder.

### ISSUE THREAD

**Issue by MRMarchivist** [collectiveaccess/providence#1466]
branch: dev/php8

Trying to import images with all the right parameters set. Media is in root import folder and appears in the UI importer but when I try to upload, it finds "0" files. Screenshot of UI is attached.

Results in warning log:

**2023-07-13 9:58:37 - WARN --> Undefined array key &quot;parameters&quot; [/var/www/html/ca/app/lib/AccessRestrictions.php:149]
2023-07-13 9:58:38 - WARN --> Undefined array key &quot;parameters&quot; [/var/www/html/ca/app/lib/AccessRestrictions.php:149]
2023-07-13 9:58:38 - WARN --> Undefined array key &quot;item_id&quot; [/var/www/html/ca/themes/default/views/bundles/hierarchy_navigation.php:92]**

Results in debug/informational log: 

**2023-07-13 10:02:47 - DEBUG --> [importMediaFromDirectory]: Args
{"sendMail":false,"sendSMS":false,"runInBackground":false,"importFromDirectory":"","includeSubDirectories":false,"deleteMediaOnImport":false,"importMode":"DONT_MATCH","matchMode":"FILE_NAME","matchType":"STARTS","ca_objects_limit_matching_to_type_ids":["28"],"ca_objects_type_id":28,"ca_objects_parent_type_id":28,"ca_objects_child_type_id":28,"ca_object_representations_type_id":138,"ca_objects_status":0,"ca_object_representations_status":0,"ca_objects_access":0,"ca_object_representations_access":0,"ca_objects_mapping_id":"","ca_object_representations_mapping_id":"","setMode":"none","setCreateName":"","set_id":"","idnoMode":"filename_no_ext","labelMode":"blank","labelText":"","idno":"","representationIdnoMode":"filename_no_ext","representation_idno":"","logLevel":"7","allowDuplicateMedia":1,"replaceExistingMedia":"","locale_id":"1","user_id":"1","skipFileList":"","importTarget":"ca_objects","progressCallback":"caIncrementBatchMediaImportProgress","reportCallback":"caCreateBatchMediaImportResultsReport"}
2023-07-13 10:02:47 - INFO --> Found 0 files in directory ''
2023-07-13 10:02:47 - INFO --> Media import processing for directory  with 0 files begun at July 13 2023 at 10:02:47 is complete**

![Screenshot 2023-07-13 101133](https://github.com/collectiveaccess/providence/assets/98621826/3141b36f-c96c-4ddd-8794-11eab4beac46)

EDIT: Managed to get upload through user upload folders, but root import folder is still not working.

**Comment by collectiveaccess** [comment]
Fix in place to pull from root.
