### ISSUE TITLE
Object_lot_x_object relationship not present for import to ca_object_lots

### ISSUE THREAD

**Issue by MRMarchivist** [collectiveaccess/providence#1480]
dev/php8 branch

When digitizing and importing a mass of historical accession records via import to ca_object_lots, I was able to find a relationship type for object lot <=> collections but not objects. The import worked but related archival objects weren't attached because of this. 

DEBUG shows the following: 

2023-08-09 10:58:05 - DEBUG --> [testington] Found existing object 00200.0.1 in DataMigrationUtils::_getID()
2023-08-09 10:58:05 - ERROR --> Relationship type is missing for ca_objects relationship

Is the relationship supposed to be missing? If so, how do I attach them to the appropriate object lot?

**Comment by kehh** [comment]
Objects have a direct link to object lots through the lot_id field if I recall correctly. So you should be able to map directly to lot_id using a splitter refinery.

**Comment by Monica-Wood** [comment]
This was raised in the chat room. @MRMarchivist  I am assuming mapping your ca_object_lots mapping to ca_objects.lot_id using the objectSplitter refinery didn't work?

**Comment by MRMarchivist** [comment]
> This was raised in the chat room. @MRMarchivist I am assuming mapping your ca_object_lots mapping to ca_objects.lot_id using the objectSplitter refinery didn't work?

I'm unsure how to use the objectSplitter without the relationship type, so I have held off in case I break my mapping somehow. If it's the case that I can just do this as lot_id and then the relationship-less splitter, I'll go ahead and do that.

**Comment by Monica-Wood** [comment]
@collectiveaccess are you able to confirm/deny if you're able to use the objectSplitter from an object_lots mapping?

**Comment by collectiveaccess** [comment]
You cannot. Objects have to be set to a lot, not the other way around.

**Comment by MRMarchivist** [comment]
> You cannot. Objects have to be set to a lot, not the other way around.

Thank you for confirming that. I will use sets to corral them!
