### ISSUE TITLE
Fatal Error in caGetDefaultLogo

### ISSUE THREAD

**Issue by willisplummer** [collectiveaccess/providence#1481]
I'm running the develop branch locally and getting this error when I visit `/providence`

```
Fatal error: Uncaught TypeError: Return value of caGetDefaultLogo() must be of the type string, null returned in /var/www/providence/app/helpers/errorHelpers.php:200 Stack trace: #0 /var/www/providence/themes/default/views/system/configuration_error_html.php(47): caGetDefaultLogo() #1 /var/www/providence/app/lib/ConfigurationCheck.php(133): require_once('/var/www/provid...') #2 /var/www/providence/index.php(53): ConfigurationCheck::renderErrorsAsHTMLOutput() #3 {main} thrown in /var/www/providence/app/helpers/errorHelpers.php on line 200
```

Was able to work around it by commenting out the call to `caGetLoginLogo` in `caGetDefaultLogo` but wanted to let you know there's a bug there

**Comment by kehh** [comment]
Do you have any config relating to logos which might be incomplete?

**Comment by willisplummer** [comment]
Yeah, I think after this I discovered that in my Dockerfile I was overwriting the config defaults instead of writing my custom config to local/app.conf -- that was probably the culprit, but it might be worth handling the possibility of a null config value rather than blowing up?
