### ISSUE TITLE
/dev/php8 tested on php7.4 fails

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1483]
Hi @collectiveaccess 

I understand that you are hoping the version 2 code will be compatible on 7.4 -> 8.2   I was having an issue and switched over to 7.4 to check on something and got this error:

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".`

Not sure which dependency it is referring to

Monica

**Comment by collectiveaccess** [comment]
You will need to re-run composer update when you switch PHP versions.

**Comment by Monica-Wood** [comment]
Thanks,  I did run the composer update again, but just realised I didn't update-alternatives to switch the default version over (I just updated the version .sock nginx was pointing to).   Have confirmed it all ok!
