### ISSUE TITLE
ca_item_tags throwing jquery error, not allowing to be selected in UI

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1493]
Jquery error when selecting an existing tag value
```
ca.relationbundle.js?rev=GIT_2.0:183 
Uncaught TypeError: Cannot read properties of undefined (reading '_type_map')
    at options.select (ca.relationbundle.js?rev=GIT_2.0:183:32)
```

I believe introduced at this commit https://github.com/collectiveaccess/providence/commit/d04c824b10e30c5705827430ff7cda31eed07654

and related to #1492

**Comment by collectiveaccess** [comment]
Just pushed a fix. Please let me know how it works for you. Thanks.

**Comment by Monica-Wood** [comment]
Working, thanks. I did have to convince it to give up it's client cache first to get it working.
