### ISSUE TITLE
dependent field visibility ca 1.8 develop branch

### ISSUE THREAD

**Issue by imeandri** [collectiveaccess/providence#1497]
Dependent field visibility does not seem to work correctly in ca.18 develop branch. Nothing happens when both in the profile and in the user interface, you set the relevant settings correctly following the manual at https://manual.collectiveaccess.org/providence/developer/dep_field.html?highlight=dependent%20field%20visibility

**Comment by collectiveaccess** [comment]
I have verified dependent field visibility works as expected in develop and dev/php8.
