### ISSUE TITLE
service.php returning fatal error on develop branch

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1502]
System set up:
- Nginx/php-fpm
- Ubuntu 22.04
- develop branch
- Pawtucket and Providence in separate directories on server, but being handled as alias in nginx configuration so Pawtucket is root domain and Provicence is sub-dir of domain. Eg.  www.example.com is pawtucket and www.example.com/providence is Providence.

When navigating to www.example.com/providence/service.php presented with an uncaught fatal error and log states `ERROR --> ApplicationException: Invalid controller path`

Expect to return JSON with something like `{"ok":false,"errors":{"message":"Action is not defined","extensions":{"category":null},"locations":null}}`

To track down that the error comes from the develop branch, I confirmed that on my dev server which is running /dev/php8 branch and php 7.4 (using same directory/nginx config setup) is working as expected as do other systems running dev/php8 code, but with different nginx config (providence being the domain root).
I then switched my dev server to the develop branch (doing the usual composer updates etc.) and it now shows the same 'uncaught fatal error'.

**Comment by Monica-Wood** [comment]
Addition to this.  It looks like the /OAI and /simple end point is still working, just not the JSON/REST API endpoints.

**Comment by kehh** [comment]
I think you have to add a `json` to the path after service.php

**Comment by kehh** [comment]
(the json services are preparing for deprecation iirc)

**Comment by collectiveaccess** [comment]
dev/php8 puts the graphql api on service.php. json services are in services.php/json

**Comment by Monica-Wood** [comment]
OK. So the reason things aren't working at service.php without the json is because the graphql hasn't been merged into develop yet?

**Comment by collectiveaccess** [comment]
yes
