### ISSUE TITLE
JPF loads as binary

### ISSUE THREAD

**Issue by teebark** [collectiveaccess/providence#1511]
Uploading an object rep used to work fine, but after installing ImageMagick, image files load in binary format and show as blank. After uninstalling ImageMagick, new reps still load as binary. I'm having trouble figuring out how to trouble shoot this. Has anyone run into this themselves? I'm on Centos 7 (but converting to Debian shortly).

https://imgur.com/YbkBbcw

**Comment by collectiveaccess** [comment]
Your ImageMagick install is probably broken.
