### ISSUE TITLE
Display Templates showing on Summary Pages even when not enabled for this view

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1513]
Setting a display template to only be usable for search results, results in it still being an option on the summary screen. However we you select it, it doesn't load.  So it's there to be selected, but doesn't work.

Is there a way to high it from the summary page display options?

**Comment by collectiveaccess** [comment]
It should hide. Someone will need to take a look at it.

**Comment by Monica-Wood** [comment]
I just did an update (dev/php8 branch) and this issues seems to be fixed sometime in the last 89 commits. Apologies, I should have done that first before reporting it, didn't realise I was so  far behind.
