### ISSUE TITLE
Duplicate items being saved into sets

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1515]
Even with the setting `allow_duplicate_items_in_sets` set to `0`, the set editor 'set items' where you search for an item to add, allows you to add the same item over and over again until you hit save.  It then saves the duplicated items into the list (instead of removing them).  Once it's saved, it then wont give you back the result of an item you already have the list (as expected).

Maybe a trigger on save to check for duplicates and remove them if `allow_duplicate_items_in_sets` is set to false.

**Comment by collectiveaccess** [comment]
I do not see this behavior on my test system running dev/php8.
