### ISSUE TITLE
PHP fatal error on Develop branch

### ISSUE THREAD

**Issue by poplarmedia** [collectiveaccess/providence#1536]
I have a fresh install of Providence Develop branch on php 7.4, and I am getting this error when I try to access the summary of a list. Have tried with Dublin Core 2018, VRA 4.0 core and default profiles, same error.

Appears similar to https://github.com/collectiveaccess/providence/issues/1418

**Log**
`2024-02-17 21:19:59 - ERROR --> ApplicationException: View does not exist`

**URL path**
`../administrate/setup/list_editor/ListEditor/Summary/list_id/##`

**Full Message**
`Fatal error: Uncaught Error: Call to undefined method ca_lists::getInstance() in /path/to/providence/app/models/ca_bundle_displays.php:2197 Stack trace: #0 /path/to/providence/themes/default/views/administrate/setup/list_editor/summary_html.php(66): ca_bundle_displays->getDisplayValue(Object(ca_lists), -1, Array) #1 /path/to/providence/app/lib/View.php(329): require('/path/to/...') #2 /path/to/providence/app/lib/View.php(297): View->_render('/path/to/...') #3 /path/to/providence/app/lib/Controller/ActionController.php(163): View->render('summary_html.ph...', false) #4 /path/to/providence/app/lib/BaseEditorController.php(782): ActionController->render('summary_html.ph...') #5 /path/to/providence/app/lib/Controller/RequestDispatcher.php(289): BaseEditorController->Summary(NULL) #6 /path/to/providence/app/lib/Controller/AppController.php(114): RequestDispatcher->dispatch(Array) #7 /path/to/providence/index.php(127): AppController->dispatch(true) #8 {main} thrown in /path/to/providence/app/models/ca_bundle_displays.php on line 2197`

**Comment by collectiveaccess** [comment]
Use the dev/php8 branch.

**Comment by poplarmedia** [comment]
Is it considered stable for production use or do we stick with r1.7.17?

**Comment by collectiveaccess** [comment]
It's what we use.

**Comment by poplarmedia** [comment]
Error still persists in /dev/php8 branch

**Comment by collectiveaccess** [comment]
I guess you have the template debugger enabled? It will throw the error when that is enabled. 4a5732131ffbfd07d254612517a36ce8326b9fa8 resolves it.
