### ISSUE TITLE
Logo does not hyperlink back to home page when clicked

### ISSUE THREAD

**Issue by poplarmedia** [collectiveaccess/providence#1538]
In dev/php8 if when I click on the C/A logo, it will not take me back to home page from the page I am on.
BROWSER 
FireFox (latest)
Chrome (latest)

OS
MacOS Sonoma

**Comment by collectiveaccess** [comment]
Try doing a pull to use current code. This works fine for me.

**Comment by poplarmedia** [comment]
Pulled the code today, working again, Thanks!
