### ISSUE TITLE
'ERROR--> ApplicationException: Action is not defined' when accessing Media Submissions in Menu

### ISSUE THREAD

**Issue by poplarmedia** [collectiveaccess/providence#1539]
Experiencing Fatal error in dev/PHP 8, latest build. 

When trying to access 'Manage>>Media Submissions' from the menu.

`Fatal error: Uncaught Error: Class 'Firebase\JWT\JWT' not found`

Log is showing: 
`ERROR --> ApplicationException: Action is not defined`

URL: .../manage/Submissions/Index.php

**Comment by collectiveaccess** [comment]
This is a feature for a specific user. We'll remove.
