### ISSUE TITLE
[Feature request] Restart unfinished processes on widget

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1556]
Just brainstorming and thought I would place it here for "future".

Would be great to have an easy way for admin staff to unstick stalled processes from the queue without needing to ssh and run the caUtils.

Would it be possible to put a button on the processing status widget (if admin user) to 'restart unfinished processes' if any processes have a start time longer ago than $process_stalled_time ?

This would then trigger the `caUtils process-task-queue -r` 

Thoughts?

**Comment by collectiveaccess** [comment]
A restart button for "stuck" processes was recently added. Is that not working for you?

**Comment by Monica-Wood** [comment]
oooo, exciting. I haven't gone looking for it, the install that triggered me to think about it is on develop from a couple of months ago, so doesn't have this.   But I can confirm I see it on my dev/php8 Development server.  Thank you :D
