### ISSUE TITLE
PHP Error in loadExporterByCode() breaks download of object representations files in CA 2.0

### ISSUE THREAD

**Issue by amergelCGI** [collectiveaccess/providence#1557]
In CA 2.0 (dev/php8), a PHP error occurs when trying to download object representations media files.

Fatal error: Uncaught TypeError: ca_data_exporters::exportRecord(): Argument #1 ($exporter_code) must be of type string, array given, called in /var/www/html/collectiveaccess/app/helpers/mediaPluginHelpers.php on line 902 and defined in /var/www/html/collectiveaccess/app/models/ca_data_exporters.php:1148 

Stack trace: 
#0 /var/www/html/collectiveaccess/app/helpers/mediaPluginHelpers.php(902): ca_data_exporters::exportRecord() 
#1 /var/www/html/collectiveaccess/app/helpers/mediaPluginHelpers.php(827): caExportMediaMetadataForRecord() 
#2 /var/www/html/collectiveaccess/app/lib/BaseEditorController.php(2548): caEmbedMediaMetadataIntoFile() 
#3 /var/www/html/collectiveaccess/app/lib/Controller/RequestDispatcher.php(289): BaseEditorController->DownloadMedia() #4 /var/www/html/collectiveaccess/app/lib/Controller/AppController.php(108): RequestDispatcher->dispatch() 
#5 /var/www/html/collectiveaccess/index.php(128): AppController->dispatch() 
#6 {main} thrown in /var/www/html/collectiveaccess/app/models/ca_data_exporters.php on line 1148

This is due to an array passed to $ps_exporter_code which is expected to be a string in function loadExporterByCode() in app/models/ca_data_exporters.php.
This caused only a warning in PHP 7 but it became an error since PHP 8.

Here is some debug info that might be helpful:

json representation of $ps_exporter_code: 
{"XMP:Title":{"ca_objects.preferred_labels.name":[]},"XMP:Description":{"ca_objects.description":[]},"XMP:Rights":["static:(c) 2011"],"XMP:Creator":{"ca_entities.preferred_labels.displayname":{"delimiter":","}},"XMP:Subjects":{"ca_list_items.preferred_labels.name_plural":{"delimiter":","}}}

![Bug](https://github.com/collectiveaccess/providence/assets/149600591/e971bf1a-814a-4406-b5b7-e178e7656be3)
![Bug2](https://github.com/collectiveaccess/providence/assets/149600591/7edd7d15-d8c6-4088-8c1a-5929c737986b)

**Comment by amergelCGI** [comment]
Issue is still occuring with the latest code. I am not sure what exactly is supposed to be the exporter code. Can it be for example "XMP"?

**Comment by collectiveaccess** [comment]
What does your `media_metadata.conf `file look like?

**Comment by amergelCGI** [comment]
```conf
extract_embedded_exif_georeferencing_to = []
extract_embedded_exif_georeferencing_to_container = {
}

extract_embedded_exif_creation_date_to = [ca_object_representations.media_creation_date]
extract_embedded_exif_creation_date_to_container = {
}

import_mappings = {
	ca_object_representations = {
		__default__ = {
			EXIF:IPTC:CopyrightNotice = {
				ca_object_representations.media_copyright
			},
			EXIF:IPTC:By-line = {
				ca_object_representations.media_author
			},
			EXIF:IPTC:Source = {
				ca_object_representations.media_source
			},
			EXIF:IFD0:Model = {
				ca_object_representations.media_model
			},
			EXIF:ExifIFD:ColorSpace = {
				ca_object_representations.media_color_space
			},
			EXIF:System:FileName = {
				preferred_labels.name
			},
			EXIF:System:FileSize = {
				ca_object_representations.media_file_size
			},
			EXIF:File:ImageWidth = {
				ca_object_representations.media_image_width
			},
			EXIF:File:ImageHeight = {
				ca_object_representations.media_image_height
			},
		}
	}
}

export_mappings = {
	ca_objects = {
		__default__ = {
			XMP:Title = {
				ca_objects.preferred_labels.name = {}
			},
			XMP:Description = {
				ca_objects.description = {}
			},
			
			XMP:Rights = {
				static:(c) 2011
			},
			XMP:Creator = {
				ca_entities.preferred_labels.displayname = {
					delimiter = ", "
				}
			},
			XMP:Subjects = {
				ca_list_items.preferred_labels.name_plural = {
					delimiter = ", "
				}
			}
		}
	}
}
```

**Comment by amergelCGI** [comment]
Your latest commit fixed my issue,
Thank you for your support
