### ISSUE TITLE
3rd-Party Tracking Installed by login.css

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1567]
https://github.com/collectiveaccess/providence/blob/d62ff170859d67555baf171ddcb5d494c59d2593/themes/default/css/login.css#L1

This line of code is designed to look like a CSS inclusion, but the server always returns an empty payload.  If the client does not provide a cookie, the server sets a cookie.

In other words, it provides a 3rd-party web tracker and does nothing else.

**Comment by Monica-Wood** [comment]
This doesn't seem to be in the develop or dev/php8 branch, so looks like it's been removed.
