### ISSUE TITLE
fsockopen a Weak Choice for IPv6 Environments

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1571]
https://github.com/collectiveaccess/providence/blob/d62ff170859d67555baf171ddcb5d494c59d2593/app/lib/Controller/Request/RequestHTTP.php#L674

This implementation of the out-of-process indexing trigger leaves much to be desired.  In dual stack hosts, the originating address becomes fairly unpredictable, which can be a problem for security configuration.  In other words, I want to make an htaccess exception to allow these requests, but the client address changes randomly, and I don't want to allow the entire local subnet.

I suggest changing this to cURL or the HTTPMultiClient where there is at least enough flexibility to force IPv4 name resolution when needed.

**Comment by collectiveaccess** [comment]
It's completely different in the dev/php8 (to be v2.0) code and does not depend upon network connections as the 1.7 code does.
