### ISSUE TITLE
incorrect labels being set on install

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1574]
This is a new one. 
When dong a new install, if you don't explicitly set a label in the `placement` bundle settings, it will use the label from the previous placement bundle. Even though the label is set in the `metadataElement`

dev/php8

**Comment by collectiveaccess** [comment]
I cannot reproduce this. Please send me the profile you were loading when you saw this happen.

**Comment by Monica-Wood** [comment]
Emailed to you

**Comment by collectiveaccess** [comment]
Thanks. I was able to find the problem.
