### ISSUE TITLE
IDNO Indexing 

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1586]
I am trying to work out how to get the system to index each section of an IDNO separately.  

EG. if your idno for occurrence was 'EXH.SMI.2023.007'  and you search on SMI it would return that occurrence record.

I have tried setting the delimiter in multipart_id_number.conf (even though not really using this functionality)
and I have tried setting the `IDNO_DELIMITERS=["."]` in the ca_occurrences block of search_indexing.conf for IDNO.   
(and tried having them both set).  Each time after reindexing it's still not showing when searching on that middle value.

Am I missing something? should these settings enable this search indexing functionality?

**Comment by collectiveaccess** [comment]
It does it incrementally as @kehh wrote. It never occurred to us to indexing components separately. For most(?) users this would provide undesirable search results. If you need an option added to support this we can add it.

**Comment by Monica-Wood** [comment]
Thanks @kehh and @collectiveaccess.  I completely understand why it wouldn't be indexed that way, with search results bringing back all sorts of things.  But when I read in the `search_indexing.cong` the following description of the setting:
```
IDNO_DELIMITERS   if set to a list of delimeters and INDEX_AS_IDNO is set, value will be split on the delimiter and resulting components indexed separately
```
I thought that maybe this was a setting that allowed it.  

I have done some search query testing and it seems to work perfectly fine if searching for the middle components using wild cards. eg `*.SMI.*` to bring back relevant results.
