### ISSUE TITLE
Set of list_items only shows one in set items list

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1592]
Creating a set of list items and then viewing this list under Items > Set items will only show one item.
It shows there are more items in the set and bulk edits work over all items, it just show only one item.

<img width="1017" alt="Screenshot 2024-07-03 at 8 39 05 AM" src="https://github.com/collectiveaccess/providence/assets/25235893/8999a359-48fd-4c18-84f1-dcb9503bad47">

**Comment by collectiveaccess** [comment]
Just pushed a fix for this.

**Comment by Monica-Wood** [comment]
Thank you
