### ISSUE TITLE
Tags not being indexed correctly

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1598]
since updating an instance from php8 branch (approx 16 July), the Tags (ca_item_tags) aren't indexing correctly.  
It will only index to first record saved with that tag (or the first record since the update or last full index).  So if I search with access point tags:"tag name" it will only return one (unless there is stuff indexed prior). 

Since the upgrade I did a full reindex and everything was ok with that, so there might be an issue with incremental indexing that is working ok on a full reindex?

If I delete a tag from the item that was showing up, then try and add it again, it deletes it from the index and wont add it again.

**Comment by Monica-Wood** [comment]
Not sure if it's connected, but newly added related ca_list_items are also not indexing.

**Comment by collectiveaccess** [comment]
Pushed fix for this.
