### ISSUE TITLE
Tag creator is null for imported tags

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/providence#1599]
Discovered that if you import tags with a bulk metadata import, then you try and save another tag in the same record some time later, you get the following error message:

```
There are errors preventing information in specific fields from being saved:
Related tags: Tag was not created by specified user
Related tags: Tag was not created by specified user
```
![Screenshot 2024-08-06 at 10 50 17 AM](https://github.com/user-attachments/assets/81cdebaa-3718-47aa-94a0-57287dcddf23)
Message is twice, because there are 2 tags previously loaded with import.

the `user_id` and moderated_by_user_id` is NULL in the database.

either, there is no check on if the tag has a creator, or save the importing user as the `user_id` in the database?

This is a low impact issue.

Thanks.

**Comment by collectiveaccess** [comment]
Pushed fix for this.
