### ISSUE TITLE
Can't Upgrade, caUtils throws Undefined constant "__CA_CACHE_TTL__"

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1607]
Seems to be a bug in the dev/php8 branch.

`PHP Fatal error:  Uncaught Error: Undefined constant "__CA_CACHE_TTL__" in app/lib/Cache/ExternalCache.php:297`

Interesting trace.  The post-setup.php file appears to be using the cache prior to defining the cache constants.

```
#0 app/lib/Cache/ExternalCache.php(230): ExternalCache::getApcObject()
#1 app/lib/Cache/ExternalCache.php(57): ExternalCache::getCacheObject()
#2 app/lib/Cache/ExternalCache.php(171): ExternalCache::init()
#3 app/helpers/post-setup.php(71): ExternalCache::contains()
#4 setup.php(291): require('...')
#5 support/bin/caUtils(273): require_once('...')
#6 support/bin/caUtils(34): _caUtilsLoadSetupPHP()
#7 {main}
```

https://github.com/collectiveaccess/providence/blob/c2ca6f38a8f7af9e2659e7dd16c0b5ddb1ec6710/app/helpers/post-setup.php#L72

https://github.com/collectiveaccess/providence/blob/c2ca6f38a8f7af9e2659e7dd16c0b5ddb1ec6710/app/helpers/post-setup.php#L354

Steps to reproduce:

Attempt upgrade with `setup.php` containing this block...

```
if (!defined('__CA_CACHE_BACKEND__')) { 
	define('__CA_CACHE_BACKEND__', 'apc');
}
```

Workaround:

Change `setup.php` as follows...

```
if (!defined('__CA_CACHE_BACKEND__')) { 
	define('__CA_CACHE_BACKEND__', 'apc');
}
if (!defined('__CA_CACHE_TTL__')) { 
	define('__CA_CACHE_TTL__', 3600);
}
```

**Comment by collectiveaccess** [comment]
Pushed fix setting defaults for constants before trying to access cache.
