### ISSUE TITLE
Access control type access checking for list item concepts not saving

### ISSUE THREAD

**Issue by jjs6791** [collectiveaccess/providence#1609]
I am going to Access Control --> Access Roles  --> Edit --> Types tab

Under List items, Type concepts is set to "No Access". 

I change that to "Read/edit access" and save

The change doesn't stick as going into it again shows it concepts set to "No Access"

I want my user in this role to be able to add new list items (concepts) to a list but when the screen is loaded there are no fields showing.  

I was able to change other related metadata fields, actions , etc. to grant access, but not concept so I assume that is the thing causing no fields there.

**Comment by collectiveaccess** [comment]
Make sure `max_input_vars` in php.ini is set to a sufficiently high value (trying 5000 or 10000 to see if the limit is actually the problem). When there are lots of metadata elements defined, the number of values in the role form can get large and exceed the PHP default, which is usually 2000. One of these days we'll segment the role into multiple forms to avoid hitting the limit in all cases, but that day is not today.

**Comment by jjs6791** [comment]
Thanks.  The form seems to save normally- the confirm message shows.  If it exceeded the max_input_vars would that still occur or would it show an error?

**Comment by collectiveaccess** [comment]
It'll just silently throw away values if the limit is exceeded. PHP doesn't report an error to the application, so we can't report an error to the user. I suppose we could look to see if certain keys are set and complain if they're not, but really the proper solution would be to not have a monolithic form to begin with.

**Comment by jjs6791** [comment]
Thanks, it works fine after increasing max_input_vars
