### ISSUE TITLE
UniversalViewer throwing Uncaught TypeError

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1611]
Using Providence dev/php8 branch, with the image overlay in UniversalViewer, any interaction with the overlay causes a javascript error:

```
Uncaught TypeError: dimensions is null
    getCroppedImageUri assets/universalviewer/dist/uv/lib/app.js:8298
```

I can close and re-open the viewer, but nothing else is working due to the errors.  I'm also having trouble switching viewers.  It seems like it only wants to use UniversalViewer even after changing the conf.

**Comment by collectiveaccess** [comment]
Please make sure you are passing the correct media version to the UniversalViewer. It must be "tilepic", not "compressed" or "original" as used with the default pdfjs configuration. Just tested UniversalViewer and Mirador with PDFs and they render fine when properly configured.

**Comment by miqrogroove** [comment]
So far, none of the settings in media_display.conf are having any effect.

**Comment by miqrogroove** [comment]
This problem might be specific to images.  For PDFs it shows me the original file in the pdfjs viewer.  For images, I can't get it to stop showing me the UniversalViewer even after reverting the media_display.conf to the branch version from git.

**Comment by miqrogroove** [comment]
Sorted out some confusion with the conf files.  Yes, the source is "tilepic".  Same error every time.
