### ISSUE TITLE
Translation of "form elements for print summary options form"

### ISSUE THREAD

**Issue by thCAgh** [collectiveaccess/providence#1620]
**Issue description**: While printing a PDF from summary of an object, after clicking in the upper right corner in the page icon with the adobe pdf (Download summary as PDF) i get the download options windows.
After selecting PDF under "Format" combo i get the options extracted from the @params in printTemplates/summary/ca_objects_summary.php.

**What i have tried**: Obviously without success..
- I created the entry in the .po/.mo file for the language
- Edited line 845 (this is for checkbox only, for testing purposes) of file app/helpers/printHelpers.php from:
    `$form_elements[$n] = ['label' => $p['label'], 'element' => $e];`
    to
   `$form_elements[$n] = ['label' => _t($p['label']), 'element' => $e];`

**Related support topic**: [Opened this support topic](https://support.collectiveaccess.org/d/301767-translating-form-elements-for-print-summary-options-form)

As suggested by Seth in the support topic, im opening this issue for the provision of the translation of those terms.

**Comment by collectiveaccess** [comment]
Just pushed support for localization of print template option labels and list text. For labels the syntax looks like this:

` * @param includeLogo {"type": "CHECKBOX",  "label": {"en": "Include logo?", "de": "Logo Entschließen?" }, "value": "1", "default": true}`

You can use full locale codes or just the language part. Ex. de_DE for real German, de_AT for the Austrian kind. Or just "de" for German in general.

For list options the syntax is:

`* @param quantity {"type": "LIST",  "label": { "en": "Quantity", "de": "Quantität"}, "options": { "en": {"One": 1, "Two": 2, "Three: 3 },  "de": {"Eins": 1, "Zwei": 2, "Drei": 3 }}}`

The locale rules are the same here.
