### ISSUE TITLE
CKEditor 4.22.1 security warning message in editor fields

### ISSUE THREAD

**Issue by alexshultz** [collectiveaccess/providence#1625]
Description:
I'm using CollectiveAccess version 2.0 (dev/php8)
|Component|	Version|
|---|---|
Application version	|2.0
Schema revision	|197
Release type	|GIT
System GUID	|0bcdf3bd-f932-402e-b436-fe8b0b1d4143
Last change log ID	|133663
PHP version	|8.3.11
Operating system	|Darwin PX.localdomain 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64

I'm seeing the following message in text editor fields:

"This CKEditor 4.22.1 version is not secure. Consider upgrading to the latest one, 4.25.0-lts."

This appears to be a security-related warning from CKEditor itself. The message indicates that the version of CKEditor currently used in CollectiveAccess (4.22.1) is no longer considered secure, and suggests upgrading to version 4.25.0-lts.

Given that CKEditor 4 reached its End of Life for open source versions on June 30, 2023, and version 4.25.0-lts is only available under commercial terms, I wanted to bring this to your attention for consideration in future CollectiveAccess updates.

Steps to reproduce:
1. Open any record with a text editor field
2. The warning message appears in the editor area

Is there a plan to address this in a future update? Or is there a recommended way to suppress this warning message in the meantime?

**Comment by collectiveaccess** [comment]
We are working on migrating to a new editor component. It is not a simple drop-in replacement, however. To resolve for now edit `assets/ck/config.js` adding this line:

`config.versionCheck = false;`

Current revisions of the dev/php8 branch of CollectiveAccess already have this in place, so you must be running an older pull.

Note that there aren't any specific known security issues with 4.22.1; they've simply end-of-life'ed it. There will be no future security patches if issues are found

**Comment by alexshultz** [comment]
Fantastic! Thanks for your help. The problem is now fixed for me after I cleared my browser cache. I found the config.js file with the `config.versionCheck = false;` line already in place, but the warning persisted until I cleared the cache. I appreciate your patience and the clear explanation. This solution will likely help others facing the same issue.
