### ISSUE TITLE
Export with RepeatMapping rule

### ISSUE THREAD

**Issue by antonio-cassano** [collectiveaccess/providence#1626]
HI,
It's hard to explain but I'll try...
the export with the "RepeatMapping" rule has strange behavior
If there is a "direct child" source in the mapping, the value is exported correctly.
If the mapping is more complex and there are multiple "children that are non-parent directed" then the export does not correctly retrieve the value but the empty tag is present.
I attach an example of mapping and result used for my test, the value of "data" is always correctly valued, the same value recovered from a more complex mapping present in the "ead:unitdatestructured" tag instead fails and it is always empty.
[tmp_gerarchia_EXC_prove.xlsx](https://github.com/user-attachments/files/17148840/tmp_gerarchia_EXC_prove.xlsx)
[8-23.xml.txt](https://github.com/user-attachments/files/17148882/8-23.xml.txt)

ref:
https://support.collectiveaccess.org/d/301777-export-with-repeatmapping

**Comment by collectiveaccess** [comment]
What version of CollectiveAccess are you running?

**Comment by antonio-cassano** [comment]
dev/php8

**Comment by collectiveaccess** [comment]
I have just pushed a fix for this to dev/php8

**Comment by antonio-cassano** [comment]
ok it works!
many many thanks!!!!
