### ISSUE TITLE
Entity access is not definable

### ISSUE THREAD

**Issue by RetroAND** [collectiveaccess/providence#1630]
I am testing version 1.8 for a project I have in mind. Profile is ISAD(G). While in Pawtucket2 I didn't found a way for entities to be listed. I traced the source of the issue to Providence: access is defined on creating the entity, is set to "not accessible to public" and cannot be changed neither on creation nor thereafter. The solution would be creating a field to deal with the access so it could be redefined.

**Comment by collectiveaccess** [comment]
The ISAD(G) profile doesn't include the "access" field on its entity records. You can simply add it in the user interface editor.

**Comment by RetroAND** [comment]
Sorry for the trouble. I should pay more attention from now on.
