### ISSUE TITLE
/dev/php8 objectRepresentation batch editor fails, creating set with no contents

### ISSUE THREAD

**Issue by 0nobody0** [collectiveaccess/providence#1634]
using the providence /dev/php8 branch i attempted to create a set to batch edit object representations and got this error:

```
Cannot batch edit in /usr/share/nginx/html/providence/app/controllers/batch/EditorController.php line 243:

    In EditorController->_initView() in EditorController line 67
    At EditorController->Edit() in RequestDispatcher line 289
    At RequestDispatcher->dispatch() in AppController line 108
    At AppController->dispatch() in index line 128
```

creating object sets or creating sets manually seems to work fine.

looking at Manage->My Sets->All Sets the new set appears to have been created with no items in it:

![image](https://github.com/user-attachments/assets/577ba305-5aab-480f-99c5-77eb7b718794)

attempting to delete the individual set results in:

> Fatal error: Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, null given in /usr/share/nginx/html/providence/app/helpers/displayHelpers.php:1425 Stack trace: #0 /usr/share/nginx/html/providence/themes/default/views/manage/sets/widget_set_info_html.php(29): caEditorInspector() #1 /usr/share/nginx/html/providence/app/lib/View.php(329): require('...') #2 /usr/share/nginx/html/providence/app/lib/View.php(297): View->_render() #3 /usr/share/nginx/html/providence/app/lib/Controller/ActionController.php(157): View->render() #4 /usr/share/nginx/html/providence/app/controllers/manage/sets/SetEditorController.php(439): ActionController->render() #5 /usr/share/nginx/html/providence/app/lib/AppNavigation.php(469): SetEditorController->Info() #6 /usr/share/nginx/html/providence/themes/default/views/pageFormat/sideBar.php(17): AppNavigation->getHTMLWidgets() #7 /usr/share/nginx/html/providence/app/lib/View.php(329): require('...') #8 /usr/share/nginx/html/providence/app/lib/View.php(297): View->_render() #9 /usr/share/nginx/html/providence/app/lib/PageFormat.php(107): View->render() #10 /usr/share/nginx/html/providence/app/lib/Controller/RequestDispatcher.php(300): PageFormat->postDispatch() #11 /usr/share/nginx/html/providence/app/lib/Controller/AppController.php(108): RequestDispatcher->dispatch() #12 /usr/share/nginx/html/providence/index.php(128): AppController->dispatch() #13 {main} thrown in /usr/share/nginx/html/providence/app/helpers/displayHelpers.php on line 1425

after replicating the issue and having 2 sets with no content, it is possible to delete the sets together by selecting both and choosing delete from the dropdown.

setup:
- nginx 1.20.1
- mariadb 10.5.22
- php 8.3.12

**Comment by collectiveaccess** [comment]
The initial error you received will happen when the account you're using attempts to batch edit something for which it does not have batch editing privileges. I've checked and the UI options for doing batch edits are correctly not shown for accounts lacking the priv. Were you messing with privilege settings as you were doing this?

The second error could triggered for invalid sets that lack a valid label. Not sure how you created them, but I can't reproduce any of this following the steps you've described. I'm testing with PHP 8.3 as you are. I am using MySQL 8.3, not MariaDB, but I don't believe that is significant I suspect this all may be down to your specific profile setup and configuration.

I've added a change so at least we don't barf on invalid sets. The "Cannot batch edit" error appears to be appropriate.

**Comment by 0nobody0** [comment]
thanks, will take a closer look. i was testing with the administrator account automatically created after a fresh install using the built in cdwa lite 1.1 profile.

**Comment by collectiveaccess** [comment]
The admin account would not trigger that error if it had the admin role as that role has all privs by default. So something odd is going on. Maybe try a different profile?

**Comment by 0nobody0** [comment]
tried on another VM with a similar setup but with apache instead of nginx. this time used the default install profile for the sample import tutorial, then created the 3 objects in the sample import data. the same issue persists.

i also double checked permissions for the admin user role - all system administration permissions are assigned, as expected. also tried manually assigning all permissions for object representation editing and set management with no change.

using the same set creation method (detailed below) works fine for objects and entities, this just seems isolated to object representations as far as i can tell.

1. manually uploaded 2 .jpgs as object representations for an object, then used the object representations search link on the main page to view the representation list:
![image](https://github.com/user-attachments/assets/e1dbb3ec-a872-4086-8b76-1cd50c64e552)
2. clicked 'set tools' on the left hand column:
![image](https://github.com/user-attachments/assets/77eb984f-c1cd-4029-9399-46236d07801c)
3. checked 'open set for batch editing' then clicked 'create'.
![image](https://github.com/user-attachments/assets/6c64002c-50d9-4097-8664-bc4bd6393e50)

note:
1. as a second test i tried steps 1-2 then clicked 'create' without 'open set for batch editing' checked. the confirmation shows up saying the set was created:
![image](https://github.com/user-attachments/assets/697ced32-de24-4eba-873e-e85dbe850c92)
2. however either way the set is empty (* is from 3. above, *2 is from 4.):
![image](https://github.com/user-attachments/assets/c01ad6bb-f717-4628-8145-173c177ce680)

**Comment by debashish17** [comment]
please assign it to me

**Comment by collectiveaccess** [comment]
Tried this on my set up. It works fine. No issues Sets are created properly. Do you have any local config files set?

**Comment by collectiveaccess** [comment]
Ok, I see the problem now. I had representations set to be a top-level editable record in my test environment.  You don't. Just pushed a fix for all this. It's specific to systems where reps are not enabled for top-level editing.

**Comment by 0nobody0** [comment]
thanks very much
