### ISSUE TITLE
Default Value for Cache TTL

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/providence#1640]
If I'm understanding correctly...

https://github.com/collectiveaccess/providence/blob/0dc8e52f5e038a113c4586591dd315f9ca8b639e/app/helpers/post-setup.php#L85

This is the line of code that causes my user session to fail every hour.

Shouldn't this value be something like ten times larger?

**Comment by collectiveaccess** [comment]
It's used for temporary caching. User sessions are managed separately. You can set this value to whatever you wish. Try it 10x larger and see how it goes.

**Comment by miqrogroove** [comment]
Ok my mistake then.  I thought there would be a setting related to session timeout that I could fix.  Do you know where it is?
