### ISSUE TITLE
/dev/php8 Edit My project team

### ISSUE THREAD

**Issue by antonio-cassano** [collectiveaccess/providence#1641]
Hi,
when I try to edit a project team I get this error:

Fatal error: Uncaught Error: Call to undefined method ca_user_groups::getTypeCode() in /data/www/html/cola/app/helpers/displayHelpers.php:1540 Stack trace: #0 /data/www/html/cola/themes/default/views/manage/widget_group_info_html.php(33): caEditorInspector() #1 /data/www/html/cola/app/lib/View.php(329): require('...') #2 /data/www/html/cola/app/lib/View.php(297): View->_render() #3 /data/www/html/cola/app/lib/Controller/ActionController.php(157): View->render() #4 /data/www/html/cola/app/controllers/manage/GroupsController.php(213): ActionController->render() #5 /data/www/html/cola/app/lib/AppNavigation.php(469): GroupsController->Info() #6 /data/www/html/cola/themes/default/views/pageFormat/sideBar.php(17): AppNavigation->getHTMLWidgets() #7 /data/www/html/cola/app/lib/View.php(329): require('...') #8 /data/www/html/cola/app/lib/View.php(297): View->_render() #9 /data/www/html/cola/app/lib/PageFormat.php(107): View->render() #10 /data/www/html/cola/app/lib/Controller/RequestDispatcher.php(300): PageFormat->postDispatch() #11 /data/www/html/cola/app/lib/Controller/AppController.php(108): RequestDispatcher->dispatch() #12 /data/www/html/cola/index.php(128): AppController->dispatch() #13 {main} thrown in /data/www/html/cola/app/helpers/displayHelpers.php on line 1540

**Comment by antonio-cassano** [comment]
It happens also with delete

**Comment by collectiveaccess** [comment]
Just pushed a fix for this. Thank you for reporting.
