### ISSUE TITLE
/dev/php8 ActionController.php issue when called via Ajax

### ISSUE THREAD

**Issue by antonio-cassano** [collectiveaccess/providence#1648]
Hello,
There seems to be a problem with the **ActionController.php** class (in _/app/lib/Controller/ActionController.php_):
When called via ajax it fails to retrieve the user currently logged in.

We inserted a var_dump in the constructor of the "ActionController" class for debugging purposes:

```
public function __construct($po_request, $po_response, $pa_view_paths=null) {
    var_dump("ActionController userId: '" . $po_request->user->getUserID() . "'");
    ...
```

When a page or plugin calls the class normally, the following is printed in the page's source code:

```
string(28) "ActionController userId: '1'"
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
...
```

However, when the method of a plugin (which extends the ActionController class) is called via Ajax we get null:
`string(27) "ActionController userId: ''"`

For example our plugin:
```
class CSIArchiveManagerController extends ActionController {

    public function __construct(&$po_request, &$po_response, $pa_view_paths = NULL) {
        parent::__construct($po_request, $po_response, $pa_view_paths);
        ...
    }

 	public function GetTree(){
    	var_dump("GetTree:", $this->request->user->getUserID()); 
    	...
    }
}
```

If we call the GetTree method via ajax post we get the response:

```
ActionController userId: '' <-- from the constructor of the class ActionController, already null.
GetTree:
NULL <-- from $this->request->user->getUserID() call in the GetTree method.
```

The same code in 1.7.16 version works.
How come this happens?
Thank you,
Andrea e Antonio

**Comment by collectiveaccess** [comment]
My guess is that your Ajax call is not passing the session cookie, for whatever reason. There are lots of places in the CA application where Ajax calls hit controllers, and state is maintained as usually. A whole lot of the application wouldn't work if Ajax calls were broken.

**Comment by antonio-cassano** [comment]
HI,
we solved the problem of the ajax call of our controller,
the problem turned out to be that in version 1.7.16 the call to the url of our controller was 
done using service.php, while looking at other ca 2 calls 
we noticed that the ajax calls point to index.php.

We solved it by modifying the call to point to index.php.
Thank you
