### ISSUE TITLE
Video upload: unreasonable amount of space in /tmp

### ISSUE THREAD

**Issue by pjotrek-b** [collectiveaccess/providence#182]
On a fresh installation of Providence v1.4, I've tried uploading a DublinCore "Moving Image" object.
Although "queue_enabled" is set to "1" in "app/conf/global.php", according to the [installation documentation](http://docs.collectiveaccess.org/wiki/Installing_Providence#Set_up_for_background_encoding_of_media), the browser waits forever, while **"Magick" creates a 12 GB tempfile** in "/tmp".

I guess my setup must be faulty, or is this the normal behavior?
No sarcasm here. I'm seriously asking :)

If so, could it be changed? We are planning to use it with lossless FFV1/PCM/AVI files of up to 4 hours (=approx. 100 GB per video), so I assume the memory consumption would be immense.
It works perfectly fine to transcode the videos using FFmpeg on an average PC with 4 GB of RAM and no swap configured.

The video used was from FFmpeg's sample collection:
http://samples.ffmpeg.org/benchmark/testsuite1/matrixbench_mpeg2.mpg

Many thanks and regards,
Peter B.

**Comment by pjotrek-b** [comment]
Since you closed it:
Is this fixed, or does it still require the workaround?

**Comment by skeidel** [comment]
There's nothing to fix for us here, as explained above.
