### ISSUE TITLE
Media representations editor loads slowly

### ISSUE THREAD

**Issue by gohai** [collectiveaccess/providence#185]
Loading the media page of an object with 273 representations takes 11.2 seconds wall time on the server for rendering the HTML alone. Of this time, 5.4 seconds alone is spend inside a single call to caProcessRelationshipLookupLabel, which itself fires 1644 calls to SearchResult::get (presumably SQL queries). I am no expert in the nitty-gritty details of providence, but this seems a bit excessive and slow to me, given what information the rendered HTML contains, and how crucial this page is to day-to-day operations inside providence.

Happy to try out patches, etc!

Best

**Comment by collectiveaccess** [comment]
You're running 1.4 master? In the "develop" branch this should be better ("better" = faster but still not as fast as it might be)

**Comment by gohai** [comment]
Yes, 1.4. Will try out the develop branch. Thanks!

**Comment by gohai** [comment]
Quick q: Are there any changes to the database schema between the master and the develop branch? (In other words: should I be able to switch back and forth between the two) Thanks.

**Comment by skeidel** [comment]
Yes, there are a few migrations. You can't easily go back from develop unless you restore from a backup.

**Comment by gohai** [comment]
And is following the develop branch a viable option for a project? For future changes are there only migration paths from the last stable version, and develop installations are just considered throwaways, or could one pull in develop at times and be fine? I'll definitely try it out, but even if it's better for our use case, we might need to hold out to the next release then.
