### ISSUE TITLE
Bundle JS files

### ISSUE THREAD

**Issue by gohai** [collectiveaccess/providence#189]
Right now on master, loading the media page of an object fires 43 HTTP GET requests to load various JavaScript files, and I believe this will be the same for other pages in providence. I'd love to have a straightforward way to bundle these files into a single, minified file to improve page load time.

I see that the develop branch did away with the app/conf/javascript.conf file, so not sure if this is still relevant. But if you can give me a idea how to do this cleanly, I'd love to give it a shot in master.

**Comment by skeidel** [comment]
The javascript.conf is now called assets.conf and is still there :-)

I agree that it's a lot, I'm not sure if it's a giant problem though. Once these files have been loaded once, the web server responds with a 304 on every one of the asset requests and the browser loads it from cache. The only one that goes out with actual data is the page itself.

Any potential feature pull requests should be based off develop. As far as the actual implementation goes, maybe Seth can comment on that.

**Comment by collectiveaccess** [comment]
I'd love to add bundling and minification. The assets.conf (formerly javascript.conf) file did not start out quite so large and has just grown and grown. There are a number of js libraries referenced in it that are no longer even used (or loaded), and the time is ripe for a cleanup. Any changes should be done in the develop branch though. 

If you want to take a shot at working on this we'd welcome you. If you just want it fixed then create a JIRA please. Thanks!

**Comment by kehh** [comment]
OK this got inadvertantly closed by me cherry-picking a commit from our fork (https://github.com/wamuseum/providence. The commit above (8eb9197) doesn't relate to this current issue but https://github.com/wamuseum/providence/issues/189

**Comment by skeidel** [comment]
I worked this a little bit in the https://github.com/collectiveaccess/providence/tree/dev/reorganizeAssets branch a while back. I should revive that code at some point :-(
