### ISSUE TITLE
Media representations only become visible after onload

### ISSUE THREAD

**Issue by gohai** [collectiveaccess/providence#190]
The actual list of media items only becomes visible, all at once, after each of the images is loaded and the document's onload event is fired. This can take quite a while when you have 100+ items, even when everything is in the client's cache. During the time the page is not accessible to the user.

As all the thumbnail sizes are already pre-set in the HTML rendered by the backend, I don't see why it wouldn't be possible to do the layout already on DOMContentLoaded aka $(document).ready, before the images are loaded.

As current master, the event hooks for onload seem to be in:
video.js:1857
swfobject.js:5
ckeditor.js:6

**Comment by gohai** [comment]
Video demonstration: http://sukzessiv.net/~gohai/ca/onload.mov (124 images, but everything in cache!)

**Comment by collectiveaccess** [comment]
The development version loads representations in subgroups, which sidesteps the issue you describe. We could still have it perform layout before everything is loaded, and that may still be worth it, but the incremental loading solves other problems as well.
