### ISSUE TITLE
Issue with listing deleted users

### ISSUE THREAD

**Issue by leftclickben** [collectiveaccess/providence#219]
## Steps to Reproduce

1. Login as user with administrator privileges
2. Go to Manage > Access Control, this shows the "ListUsers" page which defaults to showing "full-access" users
3. Change the dropdown at the top to "deleted"

## Expected Result

List of deleted users is displayed.

## Actual Result

Dropdown switches back to "full-access" and the list of full access (not deleted) users is shown.

## Impact

This makes it very difficult to find a deleted user.  Once a user is deleted they go into a black hole and can only be recovered by guessing URLs (i.e. go to user 1 and increment the ID in the URL until the right user is found).

**Comment by leftclickben** [comment]
This is using an unmodified release 1.5, by the way.

**Comment by collectiveaccess** [comment]
There's a fix for this in master-fix (https://github.com/collectiveaccess/providence/commit/1265d7313bfc00dcc8cd5c89ee4707dd9251d9a5)

**Comment by leftclickben** [comment]
Thanks, but unfortunately our client won't use a git version, they will only use tagged releases.  As per #215 there is also a problem with Active Directory, which they also use.

Is there any plan for a 1.5.1 release?

**Comment by collectiveaccess** [comment]
We will release 1.5.1 in the next couple of weeks as time allows

**Comment by leftclickben** [comment]
OK thanks.  I'll inform the client that we should hopefully be able to add an upgrade task into the sprint that starts in just over 3 weeks' time.  TBH this particular issue isn't a major one, but AD failing to sync groups is.

**Comment by leftclickben** [comment]
@kehh FYI

**Comment by kehh** [comment]
Thanks Seth/Ben. Maintenance releases do sound great.

**Comment by collectiveaccess** [comment]
Yes, they are the best :-)
