### ISSUE TITLE
Rendering issue with many metadata in one screen

### ISSUE THREAD

**Issue by yellowDave** [collectiveaccess/providence#224]
We noticed that if you add a lot of metadata within a screen there is a rendering problem that makes the browser terribly slow. The problem seems to be tied to the creation of the tooltip that is handled with a call to jquery for each metadata (we usually have 100/150 metadata elements). A workaround could be to disable the tooltips but the problem persists.

Dave

**Comment by collectiveaccess** [comment]
Can you give us a specific example?

**Comment by yellowDave** [comment]
Our workaround is to comment out line 116: 
$vs_buf .=  caGetTooltipJS(TooltipManager::$opa_tooltips[$ps_namespace], $vs_class); 
In /app/lib/ca/TooltipManager.php

**Comment by collectiveaccess** [comment]
Can you give us details about the context in which it gets slow? How is the screen set up, how many elements on the screen, how much metadata is in each element, etc? For most users removing tooltips is a non-starter.

**Comment by yellowDave** [comment]
Actually the problem seems to appear when there are more then 150 metadata available, we can send you our CA profile, can be useful?

Dave

**Comment by collectiveaccess** [comment]
Yes please. 

To be clear, you have 150 metadata elements on a single screen?

**Comment by yellowDave** [comment]
Not really on a single screen but available in the user interfaces where there is the metadata elements list. I can't send you the profile in this moment but we have many different CA 1.5.1 installation with different profiles having the same problem  - with 195 metadata element and the browser (Chrome or Firefox) freezing waiting for the script termination. We really need to fix it. 

Thanks,
Dave

**Comment by leftclickben** [comment]
Dave is referring to the UI Screen Editor.  We have also noticed that this is very slow.  The page loads from the server fine, but the javascript on the page, in particular the drag-and-drop metadata placement widget, is causing a long delay.  We haven't had it crash the browser yet but it seems a logical eventual result with more and more metadata elements.

**Comment by collectiveaccess** [comment]
Ah I see now. We'll look into it as time allows.

**Comment by yellowDave** [comment]
Thanks Ben! You got the problem! Do you know if it's only on 1.5.1 or also in 1.5/1.4?

Dave

**Comment by collectiveaccess** [comment]
That configuration editor hasn't changed in a while. I think it's from 1.2.

**Comment by kehh** [comment]
Yup it's been pretty slow with lots of metadata elements from around 1.3.
I've taken to doing most of my profile development using PHPStorm and it's
great XML editor which derives a whole load of rules for the file using
profile.xsd. It also means you can copy/paste and use other IDE features on
the file.

**Comment by leftclickben** [comment]
I've just fixed this problem.  PR coming soon.  It's not pretty, but it works.

**Comment by collectiveaccess** [comment]
Great. The whole screen needs a redesign, but that's not likely to happen for a bit.

**Comment by leftclickben** [comment]
Yeah this is only a few lines changed, so that the `settingsForm` (which is the form inside the popup) doesn't get inserted into the DOM until the user clicks the button to display it.  The page renders much faster now :-)
