### ISSUE TITLE
Unable to implement in Vagrant

### ISSUE THREAD

**Issue by claytonllibrar** [collectiveaccess/providence#307]
I tried to implement providence in a VM using Vagrant and VirtualBox on my Windows machine, but it doesn't appear to work. The Vagrantfile is around 2 years old, are you no longer supporting Vagrant?

**Comment by collectiveaccess** [comment]
We really haven't maintained it, as you've noted. We'll try to talk a look at it this week and get it working again.

**Comment by a-mid** [comment]
I'm also unable to get providence to run in a VM using Vagrant and VirtualBox on Windows. Vagrant is up in the command line, and the collectiveaccess VM is running in VirtualBox, but when I go to localhost:8080 it throws up "localhost is currently unable to handle this request.
HTTP ERROR 500". Am I making a mistake somewhere?
