### ISSUE TITLE
caGetOption calls are problematic

### ISSUE THREAD

**Issue by axelvnk** [collectiveaccess/providence#324]
I've been profiling providence for a couple of days now, trying to find a way to increase performance of a search that requests a lot of related data. Now I've noticed that caGetOption is getting called a lot. And when I say a lot, I mean, A LOT. 100k function calls doesn't seem very good to me. And a lot of these calls, are just to get some data from an array that the method that calls caGetOption, already has.

<img width="275" alt="screen shot 2018-02-14 at 11 37 19" src="https://user-images.githubusercontent.com/6803540/36199971-7ea5bffa-117b-11e8-9d13-3479a533b89d.png">

Opinions?

**Comment by collectiveaccess** [comment]
We're aware of this – we're using the same profiler that you are – and have had the same concerns. It's a useful convenience method in general but you're correct that in most cases in just reduces to an array access than can be inlined. That said, when we did that in various hot spots, including ones with 10's of thousands of calls in a tight loop, we didn't see any change in performance at all. The actual total time spent in caGetOptions was tiny. This work was done about a year ago, and perhaps there are cases were the above is no longer or has never been true. We'll take another look.
