### ISSUE TITLE
Installer doesn't check for a writable directory for HTMLPurifier

### ISSUE THREAD

**Issue by samwilson** [collectiveaccess/providence#326]
I get the following error on install:

> Directory providence/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in providence/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297

It seems like HTMLPurifier should be writing its cache file to `app/tmp/` instead of inside `vendor/`. Also, the recommendation for 777 permissions is not secure.

**Comment by collectiveaccess** [comment]
The library wants to write to that location. It's vendor code with its own caching system. I agree that 777 is not secure on a shared machine; we need to change that message.

**Comment by samwilson** [comment]
Thanks for the quick reply!

And it seems that other people have had similar issues: https://github.com/ezyang/htmlpurifier/issues/105

The sooner more projects switch to PSR6 the better I reckon. :-) Then you'd just need to give htmlpurifier your own cachepool object and all would be groovy.

**Comment by collectiveaccess** [comment]
Yes I agree. We're embarking now on a rewrite of how we use vendor libraries, load javascript, generate the user interface, and more. All of this was started more than 10 years ago, with layers accreting over time. It was never pretty, but is becoming less so by the day :-/

**Comment by samwilson** [comment]
:) I know the feeling! Old codebases can do one's brain in. But nil desperandum, as they say; this seems like a utterly brilliant project and something the world needs.

**Comment by collectiveaccess** [comment]
What's left of my brain thanks you.
