### ISSUE TITLE
Errno -1 (Internal error) on install

### ISSUE THREAD

**Issue by SilkAndSlug** [collectiveaccess/providence#328]
I installed CA last week, practiced with for a few days, then emptied the database and deleted the files so I could re-install with a different Profile. It didn't work. I've also tried dropping the table and recreating it; in either case, `SHOW TABLES FROM redacted` returns an empty set.

The installer gets as far as `/redacted/install/index.php?email=me%40redacted&profile=spectrum&page=2`, then returns this error:

    <b>Fatal error</b>:  Uncaught DatabaseException: Can't create table `redacted`.`ca_locales` (errno: -1 &quot;Internal error &lt; 0 (Not system error)&quot;) in /redacted/app/lib/core/Db/mysqli.php:316
    Stack trace:
    #0 /redacted/app/lib/core/Db/DbStatement.php(151): Db_mysqli-&gt;execute(Object(DbStatement), Object(DbStatement), '/*=============...', Array, NULL)
    #1 /redacted/app/lib/core/Db.php(270): DbStatement-&gt;executeWithParamsAsArray(Array)
    #2 /redacted/install/inc/Installer.php(484): Db-&gt;query('/*=============...')
    #3 /redacted/install/inc/page2.php(69): Installer-&gt;loadSchema('caGetTableToBeL...')
    #4 /redacted/install/index.php(152): require_once('/redacted...')
    #5 {main}
      thrown in <b>/redacted/app/lib/core/Db/mysqli.php</b> on line <b>316</b><br />

The relevant log appears to be /var/log/mysql/error.log, which contains one of these per attempt:

    InnoDB: Error: cannot load foreign constraint redacted/fk_ca_data_exporter_labels_locale_id: could not find the relevant record in SYS_FOREIGN

The query that appears to trigger the error is the first in `schema_mysql.sql`, i.e. "create table ca_locales". I also can't get the query to run in PHPMyAdmin, even when logged into PHPMyAdmin. Changing the name of the table in the query, e.g. to calocales, enables the query to run.

I've used git to diff last week's branch with the current HEAD, and found *no* significant changes; I also can't install from that branch. I *have* created a `phpmyadmin` table and user.

What am I doing wrong? What do I need to do to fix this (or what terms should I be searching for)?

**Comment by collectiveaccess** [comment]
What version of mysql are you running?

**Comment by SilkAndSlug** [comment]
`mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $`

**Comment by collectiveaccess** [comment]
That looks like the PHP drivers. Is your mysql installation also 5.0.12? That's quite old, and we haven't supported it in a while. You must use at least MySQL version 5.5.

**Comment by SilkAndSlug** [comment]
I created a database called redacted2, updated setup.php, and now the installer works.
