### ISSUE TITLE
Change RGB to SRGB for newer versions of ImageMagick

### ISSUE THREAD

**Issue by burki** [collectiveaccess/providence#343]
Since ImageMagick 6.7.5-5 (released early 2012), the colorspace "sRGB" has to be used instead of "RGB". (https://www.imagemagick.org/discourse-server/viewtopic.php?t=20501). If RGB is used with newer versions, images appear too dark (see https://collectiveaccess.org/support/index.php?p=/discussion/299423/providence-v1-3-now-produces-images-either-too-light-or-too-dark)

I changed

    array_unshift($va_ops['convert'], '-colorspace RGB');

to

    array_unshift($va_ops['convert'], '-colorspace sRGB');

on https://github.com/collectiveaccess/providence/blob/master/app/lib/core/Plugins/Media/ImageMagick.php#L1273

It probably makes sense to make this configurable somewhere as long as there are still systems with older versions of ImageMagick in use.

**Comment by burki** [comment]
PS: As mentioned in https://collectiveaccess.org/support/index.php?p=/discussion/299423/providence-v1-3-now-produces-images-either-too-light-or-too-dark, a corresponding change probably needs to be made on https://github.com/collectiveaccess/providence/blob/master/app/lib/core/Parsers/TilepicParser.php#L386:

    $va_ops = array('-colorspace RGB');

to

    $va_ops = array('-colorspace sRGB');

**Comment by collectiveaccess** [comment]
We can make this configurable. I've created a ticket for it: http://clangers.collectiveaccess.org/jira/browse/PROV-2630
