### ISSUE TITLE
1.7.7 finding fonts error

### ISSUE THREAD

**Issue by johntorgersen** [collectiveaccess/providence#345]
Looking for fonts in:

/themes/default/css/**din**/28EC2C_0_0.woff

instead of:

/themes/default/css/**fonts**/28EC2C_0_0.woff

**Comment by collectiveaccess** [comment]
I don't see this issue in any of our installs.

**Comment by yelto** [comment]
For default themes and installs those css font directives have been pointing to a non-existing directory for a while now...

**Comment by collectiveaccess** [comment]
Providence or Pawtucket? I'm confused.

**Comment by yelto** [comment]
Providence, don't remember about Pawtucket.

**Comment by yelto** [comment]
Here it is, on top of
 providence/themes/default/css/error.css 
in develop...

**Comment by collectiveaccess** [comment]
Ah ok. Those are not manifesting as errors in the browsers I'm testing with, but they should be fixed.

**Comment by yelto** [comment]
I doubt the presence or absence of those fonts is noticeable to anyone, particularly when the error itself commands the user attention, and worries. Then there is the issue of the callouts to myfonts.net, if they are required you might as well bin them and use the most similar of the usual fonts. With apologies to the design folks.

**Comment by yelto** [comment]
Excellent, thank you.
