### ISSUE TITLE
Type mismatch for `ca_objects.extent` bundle in ISADG profile and `BaseModel::$s_ca_models_definitions`

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#357]
While importing data on the `ca_objects.extent` field I realized that there is a mismatch between the metadata element description for `ca_objects.extent` in ISADG installation profile and the one described in the Object model PHP code.

Here it is the definition from the ISADG profile, the type is `Text`: https://github.com/collectiveaccess/providence/blob/b750d65aa2a0acd88f4b21c9df0baaee4d32754b/install/profiles/xml/isad_g.xml#L1104-L1145)

The description of the field in the model PHP code is for a `number`: https://github.com/collectiveaccess/providence/blob/13ab26b416fa58b6bc0cec11ea85a54056efb0b1/app/models/ca_objects.php#L245-L252

**Comment by collectiveaccess** [comment]
This is a legacy field from an older version of CA, which had a hardcoded notion of extent as a quantity.

CA can follow ISAD, but is not limited to it. To implement an ISAD extent field configure one as a metadata element. You'd only use the hardcoded (what we call "intrinsic") extent field if you were migrating from a (now very) old version of CA.
