### ISSUE TITLE
Coding standards and formatting

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#363]
Hi,

In order to contribute to this project I would like to avoid committing code that will not follow the coding standards of the project. I am using PHPStorm as of now and it reformats files and changes code layout.

Do you have any beatifier or template so I can automate code formatting?

I am using PHPStorm as of now, but I am open to try any other environment.

Regards.

**Comment by collectiveaccess** [comment]
There is a .editorconfig file that defines basic parameters. PHPStorm should honor these. For what it's worth, I have begun using PHPStorm/WebStorm myself... so please do keep using it on your end!

Many of the code formatting standards we've used date back quite a long time (to PHP 3 and 4 in a few cases). We are in the early stages of revising and codifying these. If you'd like to help us with this it would be much appreciated.

**Comment by miceno** [comment]
There are two options:
1. The quick one and easy one: I suggest we define a style on editconfig, we save it with the configuration, and we use it in PHPStorm. I don't feel like tidying us to a tool, but using a "standard".
2. The long one: configure a command line PHP beautifier and formatter so we make sure all code is formatted the same way. In the long term, it should be this way, since you can run it before every commit and format code automatically. But it requires more effort, I don't feel on doing it as of now.

The critical issue as of now is that if we apply any editconfig/PHPStorm formatting it will update all the source code :( and it will not be nice on the git log. 

I tried to apply any of the PHPStorm styles (PSR1/PSR2, Laravel, CodeIgniter...) and all of them introduced changes in spacing or braces location, or both :( So I don't feel like changing all the files as of now.

**Comment by miceno** [comment]
merged on #364
