### ISSUE TITLE
Recurring HTTP 500 Error using vagrant image

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#365]
Hi

I am developing (from `develop` branch) using `Vagrantfile` configuration.

I am continuously getting HTTP 500 Errors. I think they are related to the cache, but I am not familiar with it, so I don't know how to deal with them. It is not clear to me if the issue is related to something on my configuration or a latent bug on the `develop` branch.

Here it is a sample of the error on the `/var/log/apache2/error.log` file:
```
[Wed Jan 08 00:55:26.163389 2020] [php7:notice] [pid 1801] [client 10.0.2.2:58258] PHP Parse 
error:  syntax error, unexpected ''] = 1578444894;' (T_ENCAPSED_AND_WHITESPACE) in 
/vagrant/app/tmp/collectiveaccessCache/0fea6a13c52b4d47/25368f24b045ca84/38a865804f8fdcb6/57cd99682e939275/efd02694d21a801f/598ce1b6114171fe/70a527c70322dbf4/27d77c5ed98ce3de/aee6230f3abaa91f/e90ef2a0a8408df7.php 
on line 35, referer: http://localhost:8080/index.php/batch/MetadataImport/ImportData/

```
When it happens I run a `clear-caches` maintenance command and I have to reauth and run the command again, and it is solved. It is very annoying and time consuming, since it happens frequently.

Will you please advice on how to try to solve it?

I hereby attach the `app/conf/local/app.conf` file:

[app.conf.txt](https://github.com/collectiveaccess/providence/files/4049521/app.conf.txt)

Thank you in advance.

**Comment by collectiveaccess** [comment]
We are using Stash for caching (https://www.stashphp.com). The default filesystem cache driver writes a ton of tiny files with PHP code in them. I've seen errors like this when the files fail to fully write, usually when disk space runs out. I'm not sure why it would be failing to fully and correctly write these files in your set up, but in general Stash has been not entirely reliable and we're looking at alternatives. 

For now the easiest workaround for you would probably be to use redis (https://redis.io). To use it you'll need redis and the php-redis extension installed. Both of these are commonly used and typically available as packages. Once installed, you'll need to set __CA_CACHE_BACKEND__ in your setup.php file to "redis" and you should be ready to go.

There are other cachine backends available if you don't want to use redis: 'memcached', 'apc' and 'sqlite'. I've found that the performance with sqlite is terrible. The others work ok, but redis is usually be best performance coupled with easy install.

**Comment by miceno** [comment]
Thank you!

I will give `redis` a try, and in that case, I will update `Vagrantfile` to also deploy it in case it is not deployed yet.

**Comment by miceno** [comment]
Moved to `redis` and it is working like a charm :) 

Thank you again!
