### ISSUE TITLE
Advice on how to update locale

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#367]
Hi,

I am preparing to create the `ca_ES` locale and I would like to know how do you create the POT file. My intuition is that the `app/locale/en_US/message.po` is the POT file, but not sure about it.

I read the documentation at https://docs.collectiveaccess.org/wiki/Creating_a_Translation , but it does not give details, it only mentions `gettext` tools, but not the command to generate them, nor a script to run it.

I started from the `es_ES` translation, and I would like to update the strings, since I have seen that there are new commits like the one at collectiveaccess@3a81b172a3c3c1079df4430ee25a06eb422fceb7 (see comment https://github.com/collectiveaccess/providence/commit/3a81b172a3c3c1079df4430ee25a06eb422fceb7#r36758368).

Will you please advice on how to update `es_ES` with these changes?

**Comment by collectiveaccess** [comment]
Usually we just run POEdit over the source code. Open the .po file in POEdit and update from source. That will give you the .mo file you require. If you prefer I can run them this week and commit to Git.

**Comment by miceno** [comment]
Ok, no problem, I will use POEdit to update the source code!

Thank you!
