### ISSUE TITLE
Demo is outdated

### ISSUE THREAD

**Issue by cutterkom** [collectiveaccess/providence#370]
Your project is very interesting, unfortunately the demo is not working anymore and needs to be updated: https://demo.collectiveaccess.org/

**Comment by collectiveaccess** [comment]
What is the error you are receiving? It's working fine we I just looked.

**Comment by cutterkom** [comment]
the error was something an outdated database... 
weird, it's working now as well. sorry!

**Comment by collectiveaccess** [comment]
It reloads the data set every morning. You may have caught it as it was reloading.
