### ISSUE TITLE
Web API - Preferred Labels Output Issue

### ISSUE THREAD

**Issue by psdantonio** [collectiveaccess/providence#389]
I'm in the middle of writing up a python wrapper for the API -- so my proficiency is certainly not php! -- and I came across an issue where only the display name of a label will return. (i.e. forename, middlename, surname, etc. all return null). Since I am requesting the api via "format=edit" for the purposes of making a tweak and sending back the changes, currently working this way erases the other fields. I confirmed this issue on both my setup and the CA demo.

If I'm not mistaken, adding **"assumeDisplayField" => false** to the two $va_labels pulls in the getItemInfoForEdit() function in ItemService.php should do the trick! I'm not sure how many people rely on the web API, but figured I share in case it could help.

**Comment by collectiveaccess** [comment]
Yes, that's a problem. Can you do a pull request or shall we make a patch?

**Comment by psdantonio** [comment]
I don't have the repo set up on my home station -- teleworking! -- so perhaps you can handle the patch when you get a chance?

Thanks!

**Comment by collectiveaccess** [comment]
Yes, will do. Thanks for raising this issue.

**Comment by collectiveaccess** [comment]
This has been added to the develop branch.
