### ISSUE TITLE
Weird `%` chars on messages and other issues

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#392]
Hi,

Using code from `develop` branch.

I am moving an element on the place authority, and I get an unformatted string, like 

```
Will be moved under %1 after next save.
```

See attached picture for an example:
![image](https://user-images.githubusercontent.com/315830/79485875-32e92f00-8016-11ea-933a-dd4d41b12c61.png)

The URL is:
http://localhost:8080/index.php/editor/places/PlaceEditor/Edit/Screen59/place_id/2

It is not clear to me if it is something related to locales or some bug in the code.

I also noticed that when I create a place in the place authority, I fill in the "place identifier" field, but after sending the form, the field is empty :(  See attached image for the data in the form

![image](https://user-images.githubusercontent.com/315830/79487083-f7e7fb00-8017-11ea-9e20-26255bf6a705.png)

And this is after sending the form, the "place identifier" field is empty:
![image](https://user-images.githubusercontent.com/315830/79487159-1817ba00-8018-11ea-871a-285d10c288ed.png)

The point is that I also realized there are some other `%1` appearing on logs, for example, when running a data import using a mapping, with full DEBUG log, you will find lines like these:

```
log_2020-04-14.txt:2020-04-14 16:24:04 - DEBUG --> Finished building content tree for % at    0.1004 seconds [10]
```

I am sure that this message in the past was showing the name of the entity (idno) properly on the place of the `%` sign. See this log I had from previous versions:

```
log_2020-04-14.txt:2020-04-14 18:54:28 - DEBUG --> Finished building content tree for 0000000029 at    0.0093 seconds [29]
```

The date is not relevant, since I use to merge from the upstream branch some days after it is updated.

So I think it is something on the latest code, so I reviewed the commits, but I didn't find the reason.

I don't know if those three issues are connected, but I would appreciate some feedback.

Regards.

**Comment by collectiveaccess** [comment]
There are several different issues here. To take them one by one:

1. "Will be moved under %1 after next save."

This is a regression caused by a recent change in the string format elsewhere to support configurable "current location" display. A patch for this will in develop later today.

**Comment by collectiveaccess** [comment]
2. "I also noticed that when I create a place in the place authority, I fill in the "place identifier" field, but after sending the form, the field is empty :("

My first guess would be that you don't have a policy for idno's for ca_places defined in your multipart_id_numbering.conf?

What you describe happens when there's no config. We do need to handle that case better.

**Comment by collectiveaccess** [comment]
I just modified things to treat that field as a simple text field when no config is present.

**Comment by collectiveaccess** [comment]
3. There have been changes in logging that might be causing some of this. The "%" in your logs will happen if no idno is mapped though – "%" is the auto-generated numeric idno placeholder.

**Comment by collectiveaccess** [comment]
That said I just did notice a problem and will push it in a sec. Let me know if it helps.

**Comment by miceno** [comment]
> There are several different issues here. To take them one by one:
> 
> 1. "Will be moved under %1 after next save."
> 
> This is a regression caused by a recent change in the string format elsewhere to support configurable "current location" display. A patch for this will in develop later today.

Thank you!!! It works! 👍

**Comment by miceno** [comment]
> 1. "I also noticed that when I create a place in the place authority, I fill in the "place identifier" field, but after sending the form, the field is empty :("
> 
> My first guess would be that you don't have a policy for idno's for ca_places defined in your multipart_id_numbering.conf?
> 
> What you describe happens when there's no config. We do need to handle that case better.

You were right! I had a missing closing curly brace on the configuration, that was the original cause of my issues.

**Comment by miceno** [comment]
As of now it looks like it is solved. Closing the issue.

Thank you for your quick response!

**Comment by collectiveaccess** [comment]
I've changed it to react to broken numbering config better... as in it works
