### ISSUE TITLE
Import does not honor `merge_on_idno_with_replace`

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#394]
Using the latest `develop` branch code.

I am importing records with `merge_on_idno_with_replace` on but records are not updated.

I did the following. For a clean `default` profile installation I run an import of some records using a mapping. I then modifiy the mapping to set an existing field to a constant value, but records are not updated.

I am attaching the XLSX for the data and for the mapping.

Looking at the logs, there are a lot of `%` around, and I trace the code  to here https://github.com/collectiveaccess/providence/blob/43927a368cbf509c7c3659d1dd506d864683bb54/app/models/ca_data_importers.php#L1766

and it looks like the code to collect the existing record is never executed, since variable `$vb_idno_is_template` is true.

I am also attaching logs.
[log_2020-04-19.txt](https://github.com/collectiveaccess/providence/files/4498101/log_2020-04-19.txt)

Will you please have a look at it? I am afraid the latest changes introduced this regression.

[nomenclator-import.xlsx](https://github.com/collectiveaccess/providence/files/4498098/nomenclator-import.xlsx)
[poblenou-places-10.xlsx](https://github.com/collectiveaccess/providence/files/4498099/poblenou-places-10.xlsx)

**Comment by collectiveaccess** [comment]
This mapping is creating empty place records under the parents that have no label or idno. When you re-run it it tries to match on idno and of course fails. The "%" idno's in the log are what it tries on an empty identifier, assuming that you want to try and auto-generate integer idnos. If you don't have an auto-generated identifier (type=SERIAL) set up then you'll get these "%" placeholders instead.

I think you need to change your mapping to create the places referenced in column 4 in the mapping itself, and only use "parents" for columns 5, 12 and 14. Then you'll get places with proper identifiers and matching should work.

**Comment by miceno** [comment]
Thank you!

It worked!! 👍 

I followed the examples that are available on the wiki and support forum for creating a hierarchy of places and on those examples there is no recommendation for creating the idno of the imported element, they only recommend using the hierarchy builder on the parent_id of the table, but nothing else :(

I had a thorough review of the new log from importing with the new configuration (I attach files here), and I think there are some log entry that I don't fully understand, like in lines 12 and 15 of the log file
[new-log.txt](https://github.com/collectiveaccess/providence/files/4499415/new-log.txt)

I traced the message to this commit: 3a0cea5a40386e90df49aecd3859e23cdf6b1b16, but in my opinion it looks like a leftover, or it might be that I don't understand the purpose of the message ;)

Regards.

**Comment by miceno** [comment]
Closing this as it is solved, and opening a new issue for the potential leftover log #397.
