### ISSUE TITLE
Leftover log on import data

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#397]
Running on `develop` branch as of today, I had a thorough review of the log from importing with the new configuration (I will attach files later), and I think there are some log entry that I don't fully understand, like in lines 12 and 15 of the log file [new-log.txt](https://github.com/collectiveaccess/providence/files/4499415/new-log.txt)

I traced the message to this commit: 3a0cea5, but in my opinion it looks like a leftover, or it might be that I don't understand the purpose of the message ;)

**Comment by collectiveaccess** [comment]
Yes, you're right. That logging is not needed. I've removed it.

**Comment by miceno** [comment]
Thank you!

**Comment by miceno** [comment]
Closing, it is commited on develop branch
