### ISSUE TITLE
PHP 7.3 memory leak and memory limits

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#398]
Hi

I am running latest `develop` branch on PHP 7.3 in a shared hosting. I started to import a long (9300 lines) Excel file. The import started to consume more and more memory, so I suspect there is a memory leak. I attach the log (I modified the script to show memory usage).
[log-php73.txt](https://github.com/collectiveaccess/providence/files/4512116/log-php73.txt)

It stopped after 200 records and showed up a Out of Memory error, with a weird figure for the limit around 300 Mb, while my hosting allows 640Mb and so it is configured on the `php.ini` file.

I tried to figured out why it had that 300 Mb limit, but I didn't find it on the source code.

I decided to give it a try on the vagrant machine provided for developing so I run it with php 7.2 and ... tada! No memory error. I also have 7.1 on the shared hosting and it run with no leaks.

I am afraid there is something that makes it break on 7.3 but not on 7.1 nor 7.2. I didn't try on 7.4.

So this issue is about two things:
1. a suspected memory leak.
2. why there is a memory_limit different from the one setup on the `php.ini`.

**Comment by collectiveaccess** [comment]
My first guess is that PHPExcel is the problem. It does tend to eat tons of memory is certain situations. It's no longer supported, and we haven't had time to replace it with the currently supported library, PhpSpreadsheet (it's not a drop-in replacement).

**Comment by miceno** [comment]
Thank you! I agree with you, it might be PHPExcel. I had a look at the new PhpSpreadsheet, but I thought that it will be too much code to change and I am not yet too familiar with CA base code to dare into it.

Concerning the memory limit... any guess too?

**Comment by collectiveaccess** [comment]
The memory was set to force it to something that generally didn't cause errors. You might try bumping it up, or we can just try to get rid of PHPExcel.

**Comment by miceno** [comment]
I tried to change the current value but I didn't find the source code that sets it up.

Will you please advice where to change it?

**Comment by collectiveaccess** [comment]
What was the exact text of the out of memory error?

**Comment by miceno** [comment]
It is in the log file.On Apr 21, 2020 22:09, CollectiveAccess <notifications@github.com> wrote:
What was the exact text of the out of memory error?

**Comment by collectiveaccess** [comment]
Ok, and you're sure your PHP.ini is set to 640mb? There is no hardcoded memory limit of 300mb being set in CA code.

**Comment by miceno** [comment]
Yes, I raised it to 640mb but it is still on that error.On Apr 21, 2020 22:18, CollectiveAccess <notifications@github.com> wrote:
Ok, and you're sure your PHP.ini is set to 640mb? There is no hardcoded memory limit of 300mb being set in CA code.

**Comment by collectiveaccess** [comment]
Was the error for 640mb or 300mb when you raised it?

**Comment by miceno** [comment]
The error was for a memory_limit = 640Mb in php.ini, so I consider there is another limit on CA code.

**Comment by kehh** [comment]
Php excel is definitely a memory hog. I looked into this a while back and there was apparently a buffered reader that would make it more efficient. However if you change your import mapping to support CSV as well and convert the spreadsheet to CSV then memory usage stays very low. The ssconvert binary can do the conversion automatically.

**Comment by collectiveaccess** [comment]
Ok well if the error is varying based upon the php.ini setting then it's PHPExcel. I'm going to look at converting to PhpSpreadsheet in the next few days. That might help. Using CSV is also an option. It's much much less overhead.

**Comment by miceno** [comment]
Great! Thank you. I didn't consider CSV before. I will give it a tryOn Apr 22, 2020 04:13, CollectiveAccess <notifications@github.com> wrote:
Ok well if the error is varying based upon the php.ini setting then it's PHPExcel. I'm going to look at converting to PhpSpreadsheet in the next few days. That might help. Using CSV is also an option. It's much much less overhead.

**Comment by miceno** [comment]
@kehh Thank you! I will give it a try.

**Comment by miceno** [comment]
@collectiveaccess 

I had a look at PHPSpreadsheet and there are not so trivial changes like 1-based arrays (instead of 0-based) :( 

I will be happy to review the code or give you some support. Do not hesitate to involve me.

Regards.

**Comment by miceno** [comment]
Should we close this issue or should we let it open til there is a refactor for PHPSpreadsheet?

**Comment by collectiveaccess** [comment]
Let's leave this open for now. Thanks.

**Comment by collectiveaccess** [comment]
A first cut at integration of PHPSpreadsheet is in the dev/excel branch. Give it a try?

**Comment by miceno** [comment]
I will give it a try later today. Thank you!

**Comment by miceno** [comment]
I am reviewing the code, but it also includes other changes, so it is a little bit difficult to follow what it is related to the refactor and what new changes are. I will give it a try during the weekend.

**Comment by collectiveaccess** [comment]
It's based off of a branch with new features (dev/representationBundle) that is soon to be merged into develop. I wanted it to be off of that branch to allow for testing by others who are already performing testing on that branch.

What are the non-Excel changes you're seeing?

**Comment by miceno** [comment]
The changes are those of the representationBundle. I finally figured it out to locate the commit that incorporated the new PHPSpreadsheet code and I left you some comments.

**Comment by miceno** [comment]
The code is ok from my side, I think we can give it a try merging it into develop, what do you think?

**Comment by miceno** [comment]
@kehh 
> Php excel is definitely a memory hog. I looked into this a while back and there was apparently a buffered reader that would make it more efficient. However if you change your import mapping to support CSV as well and convert the spreadsheet to CSV then memory usage stays very low. The ssconvert binary can do the conversion automatically.

Thank you! I finally gave CSV a try, because I was also having headaches with date formats, and dates in CSV are stored in the display format, not in the internal Excel format.

It ran faster and more reliable, so I move my imports now to CSV.

**Comment by miceno** [comment]
Hi

I am reviewing open issues and I realized this is still here.

Did you make any progress on the PHPSpreadsheet upgrade? May I help on testing or anything?

**Comment by collectiveaccess** [comment]
Yes, we finished initial work on it and are using it for projects. It's in the dev/excel branch, also merged into dev/representationBundle (which we are using for several projects currently). Give it a try. Thanks.

**Comment by miceno** [comment]
Good! It worked! Closing this issue.
