### ISSUE TITLE
Broken code for applyRegularExpressions

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#409]
I am trying to improve code coverage and testing. I decided to start on those functions that didn't have any coverage, like `importHelpers::caProcessImportItemSettingsForValue`.

I created this test using also some descriptions that are available on the wiki:

```php
    public function testCaProcessImportItemSettingsForValue() {
        $ps_value = '7.30.smith';
        $pa_item_settings = array(
                'applyRegularExpressions' => array(
                        array("match" => '([0-9]+)\\.([0-9]+)',
                                "replaceWith" => "\\1:\\2"),
                        array(
                                "match" => "[^0-9:]+",
                                "replaceWith" => ""
                        )
                )
        );

        $result = caProcessImportItemSettingsForValue($ps_value, $pa_item_settings);
        $this->assertSame('7:30', $result);
    }

```

According to the docs, it should clean the data and return a '7:30' value.

But it doesn't. And reviewing the code I found something really weird for me, see it here:
https://github.com/collectiveaccess/providence/blob/13ab26b416fa58b6bc0cec11ea85a54056efb0b1/app/helpers/importHelpers.php#L1149-L1178

I don't quite understand lines 1164 and 1172: I think the order of parameters for `str_replace` is wrong. It should be `str_replace('\\', '\x5c', $va_regex['match'])`

And the `preg_quote` call in the following lines it is also adding additional backslash escapes, that makes the regular expressions useless.

Is it something broken or is it I didn't understand the purpose of the code?

**Comment by collectiveaccess** [comment]
Yes that's just wrong.

**Comment by miceno** [comment]
I will prepare a PR with some tests and solving it.

**Comment by miceno** [comment]
Thank you!
