### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#412]
While preparing the PR for #409, I run coverage over the tests, and it showed there is a space for improvement to make tests cover more areas.

I am incorporating those tests to the new PR and I suggest we try to improve coverage further, on every new line we add to the repository.

Improving tests is a time consuming activity, but I think the outcome is really worth the effort: confidence on refactoring and QA on every new feature we add or on every bug we solve. As of now, I don't really trust myself refactoring or solving a bug if I don't provide a test.

We can prioritize it, my suggestion is as follows:
1. most common helpers, like display, import, utilities, etc.
2. lib, we should prioritize it here too.
4. models (most used first), like entities, objects, places, etc.

In some cases it will also require some refactoring, for example, statics are difficult to deal with in unit testing, so we have to use black-box or integration tests. Mocking is a bit difficult, for example, I tried to create stubs for some of the functions on utility helpers but I needed to overwrite global functions and I can only do it safely if I refactor code to use namespaces.

What do you think?

**Comment by collectiveaccess** [comment]
I'm all for tests. The issue is time. 

What were the problems with testing on the utilityHelpers? Which ones?

**Comment by collectiveaccess** [comment]
And just to be clear: I am in total agreement with you regarding the value of a good testing suite. And I do agree with your priorities, as it follows the layering in the code.

**Comment by miceno** [comment]
Thank you!!

I will start slowly on it, as you said it takes time.

Regards.

**Comment by miceno** [comment]
> I'm all for tests. The issue is time.
> 
> What were the problems with testing on the utilityHelpers? Which ones?

I tried to start improving unit tests for `mediaPluginHelpers.php`. In order to unittest just one function like `caMediaPluginImageMagickInstalled` you should mock other functions like `caGetExternalApplicationPath`, `caIsValidFilePath` and `CompositeCache::save`; for the globals, there is no way to do it using PHPUnit, there are other PHP testing libraries that allow it, but not PHPUnit (as far as I tried it ;) ) For the static, there is a way to mock it, but it requires refactoring code to allow dependency injection.

**Comment by collectiveaccess** [comment]
I'm not sure how you'd refactor something like caMediaPluginImageMagickInstalled() to be more testable. Mocking the cache functions is straightforward, but for things that are OS/install dependent I'm not sure mocking makes sense. Of course, there are relatively few of these sort of functions, so it should be a manageable problem.

Regarding globals, I guess it's time to refactor them away. What do you think?

**Comment by miceno** [comment]
For globals, moving them to a namespace will be enough, it will allow overriding them in test code, with a technique like this (https://marcelog.github.io/articles/php_mock_global_functions_for_unit_tests_with_phpunit.html). The point is that it will mean impact many other files and that we should plan the naming strategy to be compliant with PSR4 for autoloading (I am not sure about this point, but I think I read something about it, see https://www.php-fig.org/psr/psr-4/).

Another way might be creating a Singleton with all the functions as non static members (again, a nightmare of code changes), it will allow overriding them as far as you can mock the singleton: https://qafoo.com/blog/107_refactoring_singletons_testability.html. It will allow using dependency injection, but I think it requires more effort than the namespace approach.

From my point of view the Singleton is the way, but to be honest, I think changing the current code base to use Singletons is not trivial. If I had to decide it, for now I think I will go for the namespace.

We can also give it a try on one of the helpers that is rarely used, and then decide.

**Comment by collectiveaccess** [comment]
Using a singleton means that whenever a helper is used we would need to either (a) instantiate a class and then call a method or (b) instantiate these singleton classes into globals, import those globals into scope whenever a helper needs to be called and then call a method. Putting aside questions of testability and how much work this would be to implement for a moment, both seem really ugly to actually use given how much of this code is present.

There's no reason we can't test static or global functions. The difficulties arise when those functions call other statics or globals and make it impossible to isolate dependencies. A slightly different possible approach might be to leave helpers that are "pure" (no side-effects or dependencies) as-is and test them in place. Complex helpers can be refactored into non-static methods (several of them probably belong in Base classes or, arguably, models) or spun into Singletons and modified to use dependency injection to improve testability. Separating helpers should reduce the amount of change while getting us to the same place. At least I think it will.

As you suggest, whatever approach is chosen can be evaluated on a small scale at first. It's more important to make a decision at this point than to worry if it's the right decision :-)

**Comment by miceno** [comment]
Great!

I think we should choose a function or set of functions that have very low usage, so refactoring will be easier. What do you think it might be the starting point?

**Comment by collectiveaccess** [comment]
That's a very good question. I'll have to look over and categorize the functions. My first guess would be to look at the printHelpers. They're not used a ton, and they do tend to cause problems.

**Comment by miceno** [comment]
I will give it a try on printHelpers.

**Comment by miceno** [comment]
Hi,

Giving a thought on this, I realized the code on `printHelpers.php` is confusing:

1. there is a function that is not mentioned in any other place of the entire codebase: `caPrintLabels`.
2. in `caPrintLabels` has several bugs: undefined variables; there is a reference to a function that does not exist too: `caExportAsPDF`; etc...

I was tempted to delete function `caPrintLabels`, but I don't know the history of such function, so I would like some advice on how to proceed.
