### ISSUE TITLE
Concerning command line options

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#416]
A couple of topics about command line options.

I think renaming of command line options requires further work, to make them coherent across different commands. For example, for me it is more intuitive changing `log-level|d` to `log-level|l` (`l` for level), and changing `log|l` to `log-dir|L` or `log-dir|D` (`D` for directory). 

I know that changing options may break compatibility, so I will appreciate any comments about it.

For example, in `load-import-mapping`

```bash
Options for load-import-mapping are:

	--file (-f)         Excel XLSX file to load.

	--log (-l)          Path to directory in which to log import details. If not set no logs will
	                    be recorded.

	--log-level (-d)    Logging threshold. Possible values are, in ascending order of important:
	                    DEBUG, INFO, NOTICE, WARN, ERR, CRIT, ALERT. Default is INFO.
```

`-f` is used for the source file, but on `import-media`, it is `-s`; and for `export-profile`, it is `--outputfile`.

I also consider it will be worth exploring how to implement help messages using Zend GetOpt `getUsagemessage`, and thus, remove code from `caUtils`.

**Comment by collectiveaccess** [comment]
I can't say anyone has ever given real thought to the naming of the short options. Personally I prefer the long ones, but I also spend a lot of time showing people who aren't that familiar with command line operations how to do things, so I tend to get used to typing them repeatedly :-)

There are definitely users who use the short option names (I work with a couple of them), so if we do rationalize these we'll need to make it clear in the README and also, perhaps, maintain some of the old ones for a while.

I don't believe this will be a really disruptive change though, so I am open to going ahead with it.

**Comment by kehh** [comment]
Where we have built tools around the cli we have generally used the long options.

**Comment by miceno** [comment]
Good!

I will prepare a listing of all the command line options and then share it here, so we will have a space to decide how to rearrange them.
