### ISSUE TITLE
Language fingerprints

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#422]
I found language fingerprints at https://github.com/collectiveaccess/providence/tree/develop/app/lib/Search/Common/Language/fingerprints

The point is that the Catalan language one is disabled. I would like to enable it, but it is not clear to me if I should move it to the `fingerprints` folder as `catalan.lm` or as `ca.lm`.

Is the name a country or a language code?

I would also like to know how those files were created, just in case I should also review them.

**Comment by miceno** [comment]
In fact, I just realized that piece of code is never used... :( No active code is calling `LanguageDetector` class, since `StemmingFilter` is not used also in the code.

**Comment by SethKaufman** [comment]
It was a long time ago In earlier search engines. But that was ~8 years ago
