### ISSUE TITLE
Georeference: Map drawn only partially when zooming

### ISSUE THREAD

**Issue by pjotrek-b** [collectiveaccess/providence#424]
When using the Geolocation UI widget, the map is not always drawn fully when zooming. Seems like only some map tiles are rendered.

**Example:**
  * Search for "Hackerberg"
  * Zoom in 1 level
  * Left side of the map stays gray.

Tested in Firefox and Chromium.
This behavior also appears in the Providence demo installation.

![ca-georeference_partial_map](https://user-images.githubusercontent.com/2419195/81823004-1b796500-9534-11ea-88d3-269da7566a69.png)

Setup is:

- Providence application version: 1.7.8
- Schema revision: 158
- Release type: RELEASE

**Comment by pjotrek-b** [comment]
The [documentation in the Wiki ](https://docs.collectiveaccess.org/wiki/Georeferencing) mentions configuration of OpenStreetMap tilesets in "My preferences", but I don't see this option neither in my nor in the demo installation:

Manage-->My preferences-->General-->"Map Base Layer"

**Comment by collectiveaccess** [comment]
The wiki documentation is for the older OpenLayers mapping code. You're using Leaflet. The tile server configured by default for Leaflet is no longer providing full/free access.

In app.conf set leaflet_base_layer = https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png and you should be good.

**Comment by pjotrek-b** [comment]
Thanks for the super quick reply!
That did work :smile:

The current out-of-the-box setting is:
`leaflet_base_layer` = https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}{r}.png`

May I ask though why both, the demo- and fresh installation code uses semi functional settings instead of OSM by default?

**Comment by collectiveaccess** [comment]
We haven't had time to do a release in a while. The develop code already has this as default.

**Comment by pjotrek-b** [comment]
Oh alright then! Thanks for clearing this up.
I'll close it then.

**Comment by collectiveaccess** [comment]
I've just updated the demo. Thanks for pointing that out. And we'll get it together for a release in May. Really!
