### ISSUE TITLE
Broken search tests after code update

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#425]
Hi,

Latest update on `develop` branch broke tests locally:

```
Testing started at 16:50 ...
/usr/local/Cellar/php@7.3/7.3.17_1/bin/php $COLLECTIVEACCESS_HOME/vendor/phpunit/phpunit/phpunit --configuration $COLLECTIVEACCESS_HOME/tests/phpunit.xml --teamcity
PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.17
Configuration: $COLLECTIVEACCESS_HOME/tests/phpunit.xml


testCaProcessRefineryAttributesWithFileType pending test

 $COLLECTIVEACCESS_HOME/tests/helpers/ImportHelpersTest.php:369
 

Must match the expected number of search results. Query was: ca_objects.coverageDates:"#1986"
Failed asserting that 0 matches expected 1.
Expected :1
Actual   :0
<Click to see difference>

 $COLLECTIVEACCESS_HOME/tests/testsWithData/AbstractSearchQueryTest.php:74
 $COLLECTIVEACCESS_HOME/vendor/phpunit/phpunit/phpunit:61
 

Must match the expected number of search results. Query was: ca_storage_location_labels.name:"Test"
Failed asserting that 0 matches expected 1.
Expected :1
Actual   :0
<Click to see difference>

 $COLLECTIVEACCESS_HOME/tests/testsWithData/AbstractSearchQueryTest.php:74
 $COLLECTIVEACCESS_HOME/vendor/phpunit/phpunit/phpunit:61
 

Must match the expected number of search results. Query was: ca_list_item_labels.name_singular:"Foo"
Failed asserting that 0 matches expected 1.
Expected :1
Actual   :0
<Click to see difference>

 $COLLECTIVEACCESS_HOME/tests/testsWithData/AbstractSearchQueryTest.php:74
 $COLLECTIVEACCESS_HOME/vendor/phpunit/phpunit/phpunit:61
 

Must match the expected number of search results. Query was: ca_entity_labels.displayname:"Homer J. Simpson"
Failed asserting that 0 matches expected 1.
Expected :1
Actual   :0
<Click to see difference>

 $COLLECTIVEACCESS_HOME/tests/testsWithData/AbstractSearchQueryTest.php:74
 $COLLECTIVEACCESS_HOME/vendor/phpunit/phpunit/phpunit:61
 


Time: 4.87 minutes, Memory: 148.50 MB


FAILURES!
Tests: 418, Assertions: 12393, Failures: 4, Incomplete: 1.

Process finished with exit code 1
```

It is also failing on building in Travis-CI, for another reason, since testing setup on Travis tries to use a cached version of the test database by default. I suggest rebuilding `develop` branch on Travis-CI settting SKIP_CACHED_PROFILE environment variable on Travis configuration.

I run tests on my fork and here it is the link: https://travis-ci.com/github/miceno/providence/jobs/334617210

There are a compatibility issue since I introduces `array_keys_first` on the testing code and it is not available for PHP 7.2. I will submit a PR for it.

**Comment by collectiveaccess** [comment]
The search changes are intentional. I am planning to update the tests when I have some time.

**Comment by miceno** [comment]
Good!!!

**Comment by miceno** [comment]
I didn't realize the changes will break testing. I know that `develop` branch it is that, development branch, so it is work in progress, but do you think there is any way we can signal that `develop` is unstable?

**Comment by collectiveaccess** [comment]
develop is stable in the sense that we want people to use it. But from time-to-time changes will break things, and it's on us to fix it quickly. Major changes get done in dev/* branches.

**Comment by miceno** [comment]
👍

**Comment by miceno** [comment]
I fully agree that `develop` is stable.

I realized I used `unstable` to mean `tests are broken` and they are not the same thing.

**Comment by miceno** [comment]
There is a broken test on `RelatedSearchQueryTest`, but I think you are already aware of it.

Closing.

**Comment by collectiveaccess** [comment]
Fixed this: https://github.com/collectiveaccess/providence/commit/62e815737b092c5ddccba196e3a99d96a58f93f3

**Comment by miceno** [comment]
Thank you! I will give it a try 👍
