### ISSUE TITLE
Progress bar over gzip

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#427]
Hi

I am running `develop` branch on a shared hosting and the progress bar doesn't show at all. The process I launch run properly, but the progress bar doesn't show and at the end I get the result.

I have run it also on the local vagrant machine, and progress bar show properly.

I was researching a bit, and the hosting provider is using a combination of nginx + gzip, so I think that is the issue, since the progress bar code is printing a javascript line to update the progress bar and relies on the server to deliver it immediately to the browser. In the case of nginx + gzip, server buffering prevents delivering it immediately, so I can't get the progress bar.

I tried to disable gzip just for one of the controllers on the hosting provider by adding this to the controller action function, and the progress bar finally showed up:

```php
    // Prevent gzip
    $this->response->addHeader("Content-Encoding", "none");
```

I think it will be trivial to add a flag to configure it on `app.conf`, something like
```
 disable_gzip_on_progress_bar = true
```

What do you think?

**Comment by miceno** [comment]
There is another way, a list of action/controllers that will issue a Content-encoding: none, so it will be the controller base class the one in charge of issuing the header, and there is no need to add more code on each controller :)

**Comment by collectiveaccess** [comment]
I would vote for controller base class approach. 

Another way would be to replace those progress bars, which are pretty hacky with something that uses ajax to poll rather than pushing javascript down an open connection and hoping it doesn't get buffered. 

Websockets are another possibility, but not one I'd want to take on as they can be challenging to get working in some environments.

I think your base controller method is probably the easiest to implement by far.

**Comment by miceno** [comment]
Hi

I thought deeply on the AJAX approach, but it requires new controllers and views, keeping track of the running status and the like.

If we were  writing the app from scratch, I will probably also go for the AJAX approach, but not as of now.

I am trying to identify the point to hook it on the ActionController class but not quite sure, should I add it to the `__call` method or to another one? Or would it be better to do it on the `AppController.dispatch` method?

**Comment by collectiveaccess** [comment]
I think dispatch.

**Comment by miceno** [comment]
Closing...
