### ISSUE TITLE
Broken tests on Travis

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#429]
Sorry to bother you with this issue

I am afraid the hack for caching the database is making tests fail on Travis.

Will you please force a build of `develop` branch adding to "Build > Settings" variable `$SKIP_CACHED_PROFILE` set to true? Then it will create the profile from scratch and update the cached one.

Once the profile dump is updated you should remove the variable from your build setup, so next time it will use the cached one.

**Comment by collectiveaccess** [comment]
I just set it and triggered a rebuild. Let's see what happens...

**Comment by miceno** [comment]
Thank you! It partially worked ;)

Database is now cached, but there are still a failing test (see #425), you mentioned you will update tests in the future, so I think this is solved as of now.

PHP 7.4 tests are broken due to the way the database is imported, I think. I will try to reproduce it locally and try to post a patch for it.

**Comment by collectiveaccess** [comment]
Yes, I have on my list to investigate that test failure. I have no done any testing with PHP 7.4 yet. I'll be interested to see what happens.
