### ISSUE TITLE
`new Configuration()` vs `Configuration::load()`

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#529]
Hi,

I have used `Configuration::load()` in some places around the code and I realized it is not loading configuration as I was expected, while `new Configuration()` does. I mean, what I expected was that `Configuration::load()` will load configuration from the file system, following the rules of reading local configuration and the like. But on the other hand it is loading configuration from cache.

Will you please help me understand what the best practice for loading configuration is?

Regards.

**Comment by collectiveaccess** [comment]
Configuration::load() loads the config file using new Configuration() and stashes the result in the memory cache, where it'll persist for the rest of the request. Subsequent calls to Configuration::load() in a request will load the config file instance in the memory cache. The rules for parsing files are the same with either Configuration::load() or new Configuration(). The only difference is the in-memory caching, which is there for performance reasons.

Note that new Configuration() also uses caching – it will only re-parse if any of the config files (local, stock, etc.) have changed. The in-memory caching of Configuration::load() is intended to avoid the overhead of repeated file system stat's used to figure out if files have changed on disk.

**Comment by miceno** [comment]
Thank you for the details!

The point is that to some extent the behaviour of both of them is different, since `load` will use the file path to query the cache, thus loading only the cached global configuration, while `new Configuration()` will try to load local or theme configuration.

I found this behaviour confusing while testing theme and local configuration overrides.

For example, if I run:

```Configuration::load()```

it will load from cache the global configuration for the default `app.conf` file.

If I run:
```new Configuration()```

it will load (probably also from cache) local configuration or theme configuration.

So I found that using `Configuration::load` will lead to not loading overrides from local nor theme configuration.

**Comment by collectiveaccess** [comment]
I don't find this to be true. Local and theme config is reflected in values loaded by Configuration::load(). If they weren't they'd never be used in the application, as Configuration::load() is used pretty much everywhere. 

Again, all Configuration::load() is doing is calling new Configuration() and stashing what it returns in the in-memory cache for the life of the current request. The idea is to minimize the overhead repeated configuration file references.
