### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by WrjdavisE** [collectiveaccess/providence#540]
Does anyone offer a service to install on a Mac?

**Comment by miceno** [comment]
Installing on a Mac is relatively easy:
1. install MySQL.
2. create the database
3. follow the installation instructions.
4. a running HTTP server

Should you plan to use it for development or as a live environment?

You will need PHP version 7.x on your Mac, but I think it is the one available in latests versions.

**Comment by collectiveaccess** [comment]
You may also find this guide helpful: https://manual.collectiveaccess.org/setup/install/Mac.html
