### ISSUE TITLE
Using ZendFramework1 from packagist

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#568]
Hi,

Have you consider adding Zend Framework as a dependency on the vendor library?

This way you will get rid of all the `require`, `include`, etc.

As of now, Zend Framework 1.12 is deprecated, but there are two available packages in packagist: the original one (1.12.20) and the one forked for Magento (1.14) supports PHP 7.3 (https://github.com/magento/zf1/releases/tag/1.14.2)

What do you think?

**Comment by miceno** [comment]
I tried magent ZF 1.14 (see https://packagist.org/packages/magento/zendframework1), but on version 1.14, magento removed some of "unused" libraries, like Lucene :( So I installed version 1.13.1 (see https://packagist.org/packages/magento/zendframework1#1.13.1) and it works, all the tests passes.

**Comment by collectiveaccess** [comment]
Perhaps we can first replace Lucene using https://github.com/smallhomelab/lucene-query-parser (or something similar). If the dependency on Zend_Lucene is removed, and all we use in the query parser at this point, the rest of the used libraries are mostly utilities like Zend_Measure, Zend_Locale, Zend_Log and Zend_Console.

**Comment by miceno** [comment]
I managed to make it run with Magento zf1 v 1.13.1 and all tests passed, so I think we can try later to remove Lucene, in a future PR.

**Comment by collectiveaccess** [comment]
Ok let's give this a try then...

**Comment by miceno** [comment]
I also updated Zend-stdlib (deprecated) and Zend-Escaper (deprecated) to Laminas packages, and all tests passed.

**Comment by miceno** [comment]
Giving up :(
