### ISSUE TITLE
Branch naming

### ISSUE THREAD

**Issue by dusta** [collectiveaccess/providence#721]
I suggest set develop in to branch (v1.8)
Master will stay but sugest to create second 1=1 branch named v1.7
Later integration with packagist.org will be more easier and clearer

Example in image 
![obraz](https://user-images.githubusercontent.com/9001348/101398720-d00f1580-38ce-11eb-9d0e-8bd3d5057533.png)

**Comment by collectiveaccess** [comment]
Yes I agree. We are actually in the midst of reassessing numbering. Develop was going to be 1.7.x, but we've come to realize it's a major release... so yeah we'll be making these branches shortly.
