### ISSUE TITLE
1.8 and 2.0 branches

### ISSUE THREAD

**Issue by tacman** [collectiveaccess/providence#733]
I've been playing around with providence for about a day, and quite like it.  I've worked on a much less sophisticated web-based museum inventory application, and have been researching how to get my existing data into Collective Access.  

I have a lot of experience with the Symfony framework, and think that I can make some contributions to CA based on that experience, and would love to chat with Seth and the other developers on the roadmap for 1.8 and 2.0.

On my development machine, I've made a few changes to the code, mostly because I've set it up to fail for things like trying to access an undefined index.  These kind of things are easy to fix, and get rid of warnings in the logs.  For example, in the Plugin Manager:

-                                       if(ApplicationPluginManager::$s_application_plugin_instances[$vs_plugin_dir]) { continue; }
+                                       if(array_key_exists($vs_app_plugin_dir, ApplicationPluginManager::$s_application_plugin_instances)) { continue; }

or (!empty()), or ??, whatever.

Before I started making pull requests, I wanted to ask what the best branch is to work on.  Also, is there a Discord or Slack channel to chat with developers?

Thanks,

Tac

**Comment by collectiveaccess** [comment]
Hi Tac,

In general please work off of the "develop" branch. This will be version 1.8 and has many many changes that aren't in the 1.7.9/master code. 

We do not have a public developer chat. There is a live support chat at https://gitter.im/collectiveaccess/support, but that's really not the place for developer communications. I think I'll go ahead and set up a Slack channel as we're already on Slack... so at the least we'll be there :-)

**Comment by collectiveaccess** [comment]
You can join the Slack channel at https://join.slack.com/t/collectiveaccessgroup/shared_invite/zt-k3cbec8z-jDNfPyXt_8y071M_~c5rsA

**Comment by raboof** [comment]
I'd be interested in joining the chat as well. Could you send me an invitation for the slack at slack@bzzt.net ? (the link above only allows logging in with google, apple, or 2 'special' domains)
