### ISSUE TITLE
removing get_magic_quotes()

### ISSUE THREAD

**Issue by tacman** [collectiveaccess/providence#741]
I was trying to clean up the logs, and wanted to get rid of the deprecation notice about magic quotes.

Magic quotes have been discouraged for a long time.  I started to make a PR for this, but realized they haven't been deprecated until php 7.4.

Can we make it a requirement that they turn magic quotes off?  Or will that break too many installations?

Unfortunately, this can't be set at runtime, but perhaps we could only check it when upgrading?

**Comment by collectiveaccess** [comment]
We son't need magic quotes, so it's ok to make it a requirement that they be disabled.
