### ISSUE TITLE
Rename "Master" to "Main"

### ISSUE THREAD

**Issue by finoradin** [collectiveaccess/providence#743]
It has become common practice to use the term "Main" rather than "Master", and GitHub has even gone so far as to make this the default behavior for new repos. It is an easy fix. If for some reason it isn't obvious why this is a good idea, [you can read about it here.](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/)

**Comment by collectiveaccess** [comment]
Ok

**Comment by collectiveaccess** [comment]
Deferring this change to January 2021, as advised by GitHub. (See https://github.com/github/renaming).
