### ISSUE TITLE
Plural forms for translations

### ISSUE THREAD

**Issue by milotype** [collectiveaccess/providence#947]
Please implement the usage of **language specific plural forms** for translation strings where plural is needed, instead of using just two separate strings for singular and plural. Many languages have more differentiated plural forms.

Example of current situation:
```
#: app/controllers/batch/MediaImportController.php:526
msgid "Skipped %1 file"
msgstr ""

#: app/controllers/batch/MediaImportController.php:526
msgid "Skipped %1 files"
msgstr ""
```

This should be implemented in the source .pot file and in the Transifex translation platform. I'm sorry I can't help with this issue, because I'm not a programmer :-(

**Comment by milotype** [comment]
Another example:

```
#: ../../app/widgets/trackProcessing/views/main_html.php:129
msgid "Jobs completed in the last %1 hours"
msgstr ""
```

I'd suggest to use plural forms wherever the plural is used in the source string, even if the singular form isn't actually needed ...

**Comment by collectiveaccess** [comment]
We'll look into how best to handle this. Thank you for your suggestions.
