### ISSUE TITLE
Problem with PDFMiner

### ISSUE THREAD

**Issue by plusin** [collectiveaccess/providence#951]
CollectiveAccess 1.7.11 (158/RELEASE) Utilities
(c) 2013-2019 Whirl-i-Gig

Can't reindex PDFs: PDFMiner is not installed.

---

I changed conf files to the route of pdfminer, but caUtils isnt working. What can i do?

**Comment by collectiveaccess** [comment]
What version of pdfminer do you have installed? And what happens when you run pdfminer on the command line?

**Comment by plusin** [comment]
python3-pdfminer

The error when i ejecute command line is: 

Can't reindex PDFs: PDFMiner is not installed.

I'm using C.A 1.7.8

**Comment by collectiveaccess** [comment]
Is PDFMiner installed and works outside of CollectiveAccess?
