### ISSUE TITLE
Implement GraphQL API

### ISSUE THREAD

**Issue by collectiveaccess** [collectiveaccess/providence#953]
Implement new API for querying, data retrieval and data update using GraphQL and JWT-based authentication. Remove all long-deprecated XML-based APIs.

**Comment by zaphoyd** [comment]
The documentation at https://manual.collectiveaccess.org/developer/web_api.html suggests: "We recommend avoiding use of this API [The legacy JSON api] for new projects." and that the GraphQL API was introduced (past tense) in version 1.8. I can't actually find version 1.8 avaliable though. I have a new project that would like to use the CA api and would prefer not writing it to an API that is deprecated.

Do you have a sense of what the timelines for an official release of this API will be? Is the graphql branch on github baked enough to begin building new integrations?

**Comment by collectiveaccess** [comment]
1.8 is the next major release, and that new services documentation refers to work in progress. We expect 1.8, and the API, to be released this summer. If you want to help test the API prior to release we'd appreciate the help, of course.

**Comment by zaphoyd** [comment]
If we wanted to do some testing with 1.8 / specifically the GraphQL api, what branch would you recommend tracking?

**Comment by kehh** [comment]
> If we wanted to do some testing with 1.8 / specifically the GraphQL api, what branch would you recommend tracking?

https://github.com/collectiveaccess/providence/tree/dev/graphql-api ?

**Comment by collectiveaccess** [comment]
You can use that if you want. We're still making a lot of changes though.
