### ISSUE TITLE
check upload_tmp_dir is writable on startup

### ISSUE THREAD

**Issue by raboof** [collectiveaccess/providence#965]
On startup, providence already checks if a number of directories are present and writable. This is very helpful. It looks like the php `upload_tmp_dir` is not checked yet, but is needed for uploading media, so that would be nice to add.

(encountered on 1.7.11, haven't checked master yet)

**Comment by SethKaufman** [comment]
We assume this is writable by default. Only a broken PHP install would not have this writable.

**Comment by raboof** [comment]
Completely agreed - it's just nice to detect such broken PHP installs as well :laughing: 

I completely understand if this is not something you want to work on, of course - just wanted to record it'd be a neat improvement, and perhaps get feedback whether a contribution adding this would be welcome.

**Comment by collectiveaccess** [comment]
Well it's easy enough to add. I can do it, unless you are so inclined.

**Comment by raboof** [comment]
I can pick it up, just to get into the flow of contributing ;). Might be a while before I get to it.

**Comment by collectiveaccess** [comment]
Perfect. Thanks for offering!
