### ISSUE TITLE
Date expression parsers dont recognize extended characters

### ISSUE THREAD

**Issue by benignigiovanni** [collectiveaccess/providence#970]
Date expressions as "prima metà del XX sec." are not correctly parsed by isset().
So I modified TimeExpressionParsers.php at rows 773 with a foreach loop in the following way:

		//if (isset($va_dict[$vs_lc_expression])) {
		//	$ps_expression = $va_dict[$vs_lc_expression];
		//}
		foreach ($va_dict as $key => $value) {
			if (mb_strtolower($key) == $vs_lc_expression)
			{
				$ps_expression = $value;
			}
		}

Please take this into consideration.
Thank you.

**Comment by collectiveaccess** [comment]
Please submit proposed code changes as pull requests. Thank you!
