### ISSUE TITLE
Pagination not working for relationship with several records

### ISSUE THREAD

**Issue by jjs6791** [collectiveaccess/providence#987]
When there are several records in a relationship, there's pagination displayed. When you click to go to the next page nothing occurs, it does not go to next page. did not see a javascript error in console. Confirmed this with different types of relationships on different screens so seems to be global problem. Using Chrome on mac. FWIW Safari didn't do any better.

on develop, last pull
https://github.com/collectiveaccess/providence/commits/44a8cba121f924e275ea94c85e1eb91fec2d3f30

**Comment by collectiveaccess** [comment]
Do another pull. We fixed this.

**Comment by jjs6791** [comment]
ok thanks for the quick update!
