### ISSUE TITLE
List attributes that use a `lookup` render setting do not sort by the list's configured sort setting

### ISSUE THREAD

**Issue by kehh** [collectiveaccess/providence#991]
BaseLookupController doesn't appear to listen to the list's specified `default_sort` but rather defaults to:
```
ca_list_items_lookup_sort
```
from app.conf.

Other render settings appear to use the correct logic.

**Comment by collectiveaccess** [comment]
It's a search result in a type-ahead so we use the configured order for that context. The list sort order is used when the list as a whole is presented. 

How do you think this should work? To me the current state makes sense, but perhaps there's a better way.

**Comment by kehh** [comment]
Happy to use the configured sort order because for all these lists we want to have them sorted alphabetically, but it does seem strange if we give users the ability to define the sort order.
