### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by collectiveaccess** [collectiveaccess/providence#992]
Current 1.7.x and develop branch (1.8) code is not compatible with PHP 8.0. The 1.8 branch must be updated for compatibility with PHP 8.0.

**Comment by zaphoyd** [comment]
I see that there was a commit about a year ago that worked on PHP 8.0 compatibility. What is the current status?

**Comment by collectiveaccess** [comment]
It's still being worked on as time allows. The changes required for compatibility are significant.
