### ISSUE TITLE
Reset button in advanced search form does not clear the search context

### ISSUE THREAD

**Issue by kehh** [collectiveaccess/providence#994]
Clicking the reset button when you open an advanced search clears out the form, but then when you do a search because there are no parameters sent CA reloads the search form with the original query rather than clearing the form out.

**Comment by collectiveaccess** [comment]
It just clears the content via javascript. The expectation is that you'd then enter something else in the form and search, setting the saved values.

**Comment by collectiveaccess** [comment]
I noticed a recent update broken the button though. That's fixed now as well.
