### ISSUE TITLE
After saving a search in search builder shows several amperands in saved search dropdown

### ISSUE THREAD

**Issue by jjs6791** [collectiveaccess/providence#995]
This came up when searching if a state is empty

![Screen Shot 2021-06-24 at 6 45 07 am](https://user-images.githubusercontent.com/2420303/123165552-bb374f80-d4b7-11eb-8fa6-e665e8ade89d.jpg)

on develop, last pull
https://github.com/collectiveaccess/providence/commits/44a8cba121f924e275ea94c85e1eb91fec2d3f30

**Comment by collectiveaccess** [comment]
Those are encoded spaces on the indent of the sub-field in the field list.  We'll have to filter those.

**Comment by collectiveaccess** [comment]
Added filtering for this.
